/**
 * Nomes em inglês dos lugares mundo afora.
 *
 * A base `GLOBAL_PLACES` guarda os nomes em português (ex: "Marselha", "Nápoles")
 * e também entradas já em inglês ("Marseille", "Napoli"). Nas páginas EN (/tide)
 * queremos sempre o nome em inglês. Estes mapas cobrem os exônimos portugueses
 * mais comuns; o que não estiver aqui permanece como está (já é o nome neutro/inglês).
 */

export const COUNTRY_EN: Record<string, string> = {
  ae: 'United Arab Emirates',
  ao: 'Angola',
  ar: 'Argentina',
  as: 'American Samoa',
  au: 'Australia',
  aw: 'Aruba',
  bb: 'Barbados',
  bd: 'Bangladesh',
  be: 'Belgium',
  bg: 'Bulgaria',
  bh: 'Bahrain',
  br: 'Brazil',
  bs: 'Bahamas',
  bz: 'Belize',
  ca: 'Canada',
  ck: 'Cook Islands',
  cl: 'Chile',
  cm: 'Cameroon',
  cn: 'China',
  co: 'Colombia',
  cr: 'Costa Rica',
  cu: 'Cuba',
  cv: 'Cape Verde',
  cw: 'Curaçao',
  de: 'Germany',
  dj: 'Djibouti',
  dk: 'Denmark',
  do: 'Dominican Republic',
  ec: 'Ecuador',
  ee: 'Estonia',
  eg: 'Egypt',
  es: 'Spain',
  fi: 'Finland',
  fj: 'Fiji',
  fr: 'France',
  gb: 'United Kingdom',
  gh: 'Ghana',
  gr: 'Greece',
  gt: 'Guatemala',
  gu: 'Guam',
  hk: 'Hong Kong',
  hn: 'Honduras',
  hr: 'Croatia',
  ht: 'Haiti',
  id: 'Indonesia',
  ie: 'Ireland',
  in: 'India',
  ir: 'Iran',
  is: 'Iceland',
  it: 'Italy',
  jm: 'Jamaica',
  jp: 'Japan',
  ke: 'Kenya',
  ki: 'Kiribati',
  kr: 'South Korea',
  lk: 'Sri Lanka',
  lt: 'Lithuania',
  lv: 'Latvia',
  ma: 'Morocco',
  mg: 'Madagascar',
  mh: 'Marshall Islands',
  mp: 'Northern Mariana Islands',
  mu: 'Mauritius',
  mv: 'Maldives',
  mx: 'Mexico',
  my: 'Malaysia',
  mz: 'Mozambique',
  na: 'Namibia',
  ng: 'Nigeria',
  ni: 'Nicaragua',
  nl: 'Netherlands',
  no: 'Norway',
  nr: 'Nauru',
  nu: 'Niue',
  nz: 'New Zealand',
  om: 'Oman',
  pa: 'Panama',
  pe: 'Peru',
  pf: 'French Polynesia',
  pg: 'Papua New Guinea',
  ph: 'Philippines',
  pk: 'Pakistan',
  pl: 'Poland',
  pr: 'Puerto Rico',
  pt: 'Portugal',
  pw: 'Palau',
  qa: 'Qatar',
  ro: 'Romania',
  ru: 'Russia',
  sa: 'Saudi Arabia',
  sb: 'Solomon Islands',
  sc: 'Seychelles',
  se: 'Sweden',
  sg: 'Singapore',
  si: 'Slovenia',
  sn: 'Senegal',
  st: 'Sao Tome and Principe',
  sv: 'El Salvador',
  sx: 'Sint Maarten',
  th: 'Thailand',
  to: 'Tonga',
  tr: 'Turkey',
  tt: 'Trinidad and Tobago',
  tv: 'Tuvalu',
  tw: 'Taiwan',
  tz: 'Tanzania',
  us: 'United States',
  uy: 'Uruguay',
  ve: 'Venezuela',
  vn: 'Vietnam',
  vu: 'Vanuatu',
  ye: 'Yemen',
  za: 'South Africa',
};

/** Exônimos portugueses → inglês. Aplicado ao `name`/`countryName` do lugar. */
const CITY_EN: Record<string, string> = {
  'Marselha': 'Marseille',
  'Nápoles': 'Naples',
  'Gênova': 'Genoa',
  'Veneza': 'Venice',
  'Lisboa': 'Lisbon',
  'Londres': 'London',
  'Hamburgo': 'Hamburg',
  'Copenhague': 'Copenhagen',
  'Atenas (Piraeus)': 'Athens (Piraeus)',
  'Istambul': 'Istanbul',
  'Cidade do Cabo': 'Cape Town',
  'Jacarta': 'Jakarta',
  'Djakarta, Java': 'Jakarta, Java',
  'Tóquio': 'Tokyo',
  'Tânger': 'Tangier',
  'Tessalônica': 'Thessaloniki',
  'Valência': 'Valencia',
  'Málaga': 'Malaga',
  'Cádiz': 'Cadiz',
  'Calcutá': 'Kolkata',
  'Antuérpia': 'Antwerp',
  'Nova York': 'New York',
  'Montevidéu': 'Montevideo',
  'Mascate': 'Muscat',
  'Singapura': 'Singapore',
  'Estocolmo': 'Stockholm',
  'Bruxelas': 'Brussels',
  'Amsterdã': 'Amsterdam',
  'Amesterdão': 'Amsterdam',
  'Haia': 'The Hague',
  'Varsóvia': 'Warsaw',
  'Praga': 'Prague',
  'Viena': 'Vienna',
  'Budapeste': 'Budapest',
  'Munique': 'Munich',
  'Roma': 'Rome',
  'Turim': 'Turin',
  'Milão': 'Milan',
  'Florença': 'Florence',
  'Sevilha': 'Seville',
  'Saragoça': 'Zaragoza',
  'Palma de Maiorca': 'Palma de Mallorca',
  'Malé': 'Male',
  'Pequim': 'Beijing',
  'Xangai': 'Shanghai',
  'Seul': 'Seoul',
  'Dacar': 'Dakar',
  'Nairóbi': 'Nairobi',
  'Moscou': 'Moscow',
  'São Petersburgo': 'Saint Petersburg',
  'Atenas': 'Athens',
  'Luxemburgo': 'Luxembourg',
};

export function enCountryName(countryCode: string, fallback: string): string {
  return COUNTRY_EN[countryCode] ?? fallback;
}

export function enPlaceName(name: string): string {
  return CITY_EN[name] ?? name;
}