/**
 * MaréAgora — Descrições únicas por porto para SEO on-page
 * Cada texto é específico para aquela localidade, evitando conteúdo duplicado.
 * Uso: importe getPortoDescription(slug) e passe para PortPageContent.
 */

const portoDescriptions: Record<string, string> = {

  // ── Região Norte ──────────────────────────────────────────────────────────

  'porto-de-belem': `Belém do Pará é uma das cidades brasileiras com maior amplitude de maré do mundo. Localizada na foz do Rio Pará, próxima à confluência com o Rio Amazonas, as marés chegam a variar mais de 4 metros entre a preamar e a baixamar em períodos de sizígia. Esse fenômeno, chamado localmente de "pororoca" nas regiões mais internas, influencia diretamente a rotina portuária, a pesca artesanal e a navegação fluvial. O porto de Val de Cães é o principal terminal de passageiros e cargas da região Norte, e o conhecimento das marés é essencial para a operação segura de embarcações no canal do estuário.`,

  'ilha-do-mosqueiro': `A Ilha do Mosqueiro, localizada a cerca de 70 km de Belém, é um destino de praia muito frequentado pelos paraenses, especialmente nos finais de semana. Por estar inserida no estuário amazônico, suas marés são influenciadas tanto pelo ciclo lunar quanto pela descarga dos grandes rios da bacia amazônica. As praias de água doce da ilha — como Praia do Paraíso e Praia Grande — têm suas condições de banho diretamente afetadas pelos horários de maré, sendo a maré cheia o período preferido pelos banhistas locais.`,

  'porto-de-vila-do-conde': `O Porto de Vila do Conde, em Barcarena (PA), é um dos terminais portuários mais movimentados da região Norte, responsável pelo escoamento de alumínio, caulim e outros minérios. Localizado no estuário do Rio Pará, o porto opera em um ambiente de marés com amplitudes elevadas, exigindo planejamento rigoroso das operações de atracação e desatracação. A variação da maré nessa região pode ultrapassar 3,5 metros, tornando o acompanhamento da tábua de marés indispensável para pilotos e práticos locais.`,

  'atracadouro-de-breves': `Breves é um município do arquipélago do Marajó, no coração do estuário amazônico. O atracadouro local é ponto de passagem obrigatório para embarcações que navegam pelos furos e igarapés da região. As marés em Breves são influenciadas pelos ciclos lunares e pela enorme massa d'água dos rios Amazonas e Pará, resultando em variações significativas que chegam a afetar o nível dos igarapés por quilômetros adentro. Pescadores e ribeirinhos da região dependem do horário das marés para suas atividades diárias de subsistência.`,

  'porto-de-santana': `O Porto de Santana, no Amapá, é o principal terminal portuário do estado e porta de entrada para o escoamento de minérios extraídos na região de Serra do Navio. Situado às margens do Rio Amazonas, próximo à sua foz norte, o porto é diretamente impactado pelas marés oceânicas que penetram rio adentro. A amplitude das marés em Santana é considerável, com variações que podem chegar a 3 metros, exigindo atenção constante dos operadores portuários e das embarcações que acessam o terminal.`,

  'igarape-grande-do-curua': `O Igarapé Grande do Curuá, localizado no litoral norte do Pará, próximo à foz do Rio Amazonas, é uma região de intensa atividade pesqueira artesanal. As marés nessa área são fortemente influenciadas pela dinâmica estuarina amazônica, com variações bruscas de nível que ocorrem duas vezes ao dia. Pescadores locais utilizam o conhecimento tradicional das marés para definir os melhores horários de lançamento de redes e armadilhas, especialmente durante os períodos de maré vazante, quando os peixes se concentram nas áreas mais rasas.`,

  'barra-norte-arco-lamoso': `A Barra Norte do Rio Amazonas, no trecho conhecido como Arco Lamoso, é uma região de navegação complexa e sensível às variações de maré. A encontro das águas do Atlântico com a descarga do maior rio do mundo cria condições únicas de corrente e nível d'água, exigindo precisão no planejamento das rotas de navegação. A tábua de marés desse ponto é referência fundamental para embarcações que cruzam a foz norte do Amazonas, incluindo navios de grande porte e embarcações pesqueiras oceânicas.`,

  'fundeadouro-de-salinopolis': `Salinópolis é o principal destino de praia do nordeste paraense, famosa pelas praias do Atalaia e Corvina. Localizada em uma região de transição entre o estuário amazônico e o litoral aberto, Salinópolis apresenta marés com amplitude moderada a elevada, com variações que influenciam diretamente as condições das praias. Na maré baixa, surgem extensas faixas de areia e piscinas naturais muito procuradas por turistas e famílias locais. O horário das marés é informação essencial para quem planeja visitar as praias da região.`,

  'ilha-dos-guaras': `A Ilha dos Guarás, no litoral paraense, é uma área de preservação ambiental importante, com manguezais densos e grande biodiversidade costeira. A região é conhecida pelo avistamento de guarás-vermelhos, aves migratórias que habitam os manguezais. As marés nessa ilha têm amplitude elevada, inundando e expondo periodicamente grandes extensões de manguezal, o que cria um ciclo vital para a fauna local — caranguejos, peixes e aves que dependem desse ritmo para alimentação e reprodução.`,

  // ── Região Nordeste ───────────────────────────────────────────────────────

  'porto-de-itaqui': `O Porto do Itaqui, em São Luís do Maranhão, é um dos portos mais importantes do Brasil e o de maior profundidade natural do país. Sua localização no Golfão Maranhense o coloca em uma das regiões de maior amplitude de maré do Brasil, com variações que podem superar 6 metros durante as marés de sizígia — um fenômeno raro em escala mundial. Essa característica torna o planejamento das marés absolutamente crítico para a operação de navios graneleiros, de contêineres e de combustíveis que movimentam bilhões de reais em carga anualmente.`,

  'sao-luis': `São Luís do Maranhão está situada em uma ilha banhada pelo Golfão Maranhense, uma das regiões com maior amplitude de maré do mundo. As praias da cidade — como Calhau, Ponta d'Areia e Araçagi — têm suas condições radicalmente transformadas pelo ciclo das marés: na maré baixa, surgem quilômetros de bancos de areia e piscinas naturais; na maré alta, o mar avança até a orla. Essa dinâmica extrema é parte da identidade cultural e turística de São Luís, e conhecer os horários das marés é essencial para aproveitar ao máximo as praias da capital maranhense.`,

  'porto-de-tutoia': `Tutóia é um município maranhense localizado na foz do Rio Parnaíba, na divisa com o Piauí, e ponto de acesso aos Lençóis Maranhenses pelo lado leste. As marés na região de Tutóia são influenciadas tanto pelo oceano Atlântico quanto pela dinâmica do Delta do Parnaíba, um dos maiores deltas em mar aberto do mundo. A variação das marés afeta diretamente a navegação pelos canais do delta e o acesso às comunidades ribeirinhas que dependem de embarcações para transporte e pesca.`,

  'terminal-da-ponta-da-madeira': `O Terminal Marítimo da Ponta da Madeira, operado pela Vale em São Luís, é o maior terminal de exportação de minério de ferro do mundo. Localizado no Golfão Maranhense, onde as marés atingem amplitudes excepcionais de até 7 metros, o terminal opera com janelas de atracação rigorosamente controladas pelos horários de preamar e baixamar. Navios do tipo Valemax, os maiores graneleiros do mundo, dependem das condições de maré para acessar com segurança o canal de navegação do porto.`,

  'terminal-da-alumar': `O Terminal da Alumar, também em São Luís, é parte do complexo industrial do Consórcio de Alumínio do Maranhão. Assim como os demais terminais do Golfão Maranhense, opera em condições de maré extremas, com variações que exigem planejamento preciso para as operações de carregamento e descarregamento de bauxita e alumina. A amplitude das marés nessa região é uma das maiores da costa brasileira, tornando a tábua de marés um documento operacional crítico para toda a cadeia logística do alumínio.`,

  'porto-de-luis-correia': `Luís Correia é um município piauiense com belas praias e o único litoral do estado. O porto local serve principalmente à pesca artesanal e ao pequeno escoamento de produção regional. As marés na costa do Piauí têm características do litoral nordestino, com variações moderadas e duas preamares e duas baixamares por dia. As praias de Luís Correia, como Atalaia e Coqueiro, têm suas melhores condições de banho nas horas próximas à preamar, quando o mar cobre as áreas rasas e a água fica mais limpa.`,

  'terminal-portuario-do-pecem': `O Terminal Portuário do Pecém, no Ceará, é um porto de águas profundas construído em mar aberto, diferente da maioria dos portos brasileiros instalados em baías protegidas. Por essa razão, suas operações são diretamente impactadas pelas condições de mar e pelas variações de maré do litoral cearense. O porto movimenta cargas diversas, incluindo combustíveis, contêineres e produtos siderúrgicos da Companhia Siderúrgica do Pecém. O acompanhamento das marés é especialmente importante para a navegação de aproximação, que ocorre em canal exposto ao mar aberto.`,

  'porto-de-mucuripe-fortaleza': `Fortaleza é a capital do Ceará e um dos destinos turísticos mais visitados do Brasil. O Porto do Mucuripe, localizado próximo ao centro da cidade, é referência de maré para todo o litoral cearense. As praias urbanas de Fortaleza — Iracema, Meireles e Futuro — têm suas condições influenciadas pelo ciclo das marés, com a maré baixa revelando piscinas naturais e a maré alta trazendo o mar até a orla. A cidade também é ponto de partida para passeios de buggy nas dunas do litoral leste e oeste, cujas melhores condições coincidem com determinados horários de maré.`,

  'porto-de-areia-branca-termisa': `Areia Branca, no Rio Grande do Norte, é conhecida como a "capital do sal" — a região é responsável por grande parte da produção de sal marinho do Brasil. O porto local, operado pela Termisa, escoa a produção salineira da região. As marés no litoral potiguar são do tipo semidiurno, com duas preamares e duas baixamares diárias. As salinas da região dependem das condições de maré para o controle do nível d'água nas estruturas de evaporação, tornando a previsão de marés uma ferramenta de gestão produtiva para a indústria salineira local.`,

  'porto-de-guamare': `Guamaré é um município do Rio Grande do Norte de grande importância para a indústria petrolífera brasileira — a região concentra campos de exploração de petróleo e gás da Petrobras. O porto local serve ao escoamento de produção e ao abastecimento das plataformas offshore. As marés no litoral de Guamaré têm variação moderada, típica do litoral nordestino, mas são monitoradas continuamente pelas operações offshore que dependem de condições seguras para transferência de pessoal e carga entre embarcações e plataformas.`,

  'porto-de-macau': `Macau, no Rio Grande do Norte, é outro município inserido na região salineira do nordeste brasileiro, com importantes salinas e uma ativa frota pesqueira. O porto de Macau é ponto de referência para pescadores que atuam na costa potiguar e na plataforma continental. A lagosta é um dos principais produtos da pesca local, e as embarcações lobeiras utilizam os ciclos de maré e lua para planejar suas saídas ao mar. A maré baixa também é o período ideal para a coleta de mariscos e crustáceos nas áreas de manguezal próximas ao porto.`,

  'porto-de-natal': `Natal é a capital do Rio Grande do Norte e um dos principais destinos turísticos do Nordeste brasileiro. O Porto de Natal, localizado no Rio Potengi, serve tanto ao tráfego comercial quanto à pesca. As praias de Natal — Ponta Negra, Areia Preta e as praias do litoral sul — têm condições fortemente influenciadas pelas marés. Os famosos passeios de buggy e jangada nas praias de Genipabu e Maracajaú têm seus melhores momentos definidos pelos horários de maré baixa, quando surgem as piscinas naturais e os recifes ficam expostos.`,

  'porto-de-cabedelo': `Cabedelo, na Paraíba, é o município mais ao norte do estado e abriga um dos portos mais tradicionais do Nordeste. Localizado na foz do Rio Paraíba, o porto é referência de maré para o litoral paraibano. A cidade é ponto de partida para passeios de catamarã ao litoral norte da Paraíba, incluindo a famosa Praia de Tambaba e o Cabo Branco — o ponto mais oriental das Américas. As condições de navegação na foz do Rio Paraíba são diretamente afetadas pelas marés, especialmente durante as sizígias, quando a corrente de vazante pode ser intensa.`,

  'porto-do-recife': `Recife é a capital de Pernambuco e uma das maiores metrópoles do Nordeste. O Porto do Recife, um dos mais antigos do Brasil, está localizado na embocadura do Rio Capibaribe. As praias do litoral pernambucano — Boa Viagem, Porto de Galinhas e Muro Alto — são famosas pelos recifes de coral que formam piscinas naturais na maré baixa, atraindo milhares de turistas por ano. O controle da maré é fundamental nesses destinos: na maré alta, os recifes ficam submersos e as piscinas somem; na maré baixa, o espetáculo dos peixes coloridos entre as rochas é o principal atrativo.`,

  'porto-de-suape': `O Porto de Suape, em Ipojuca (PE), é um dos portos mais modernos e estratégicos do Brasil, com um complexo industrial que inclui refinaria, estaleiro e diversas indústrias. Localizado a 40 km ao sul do Recife, o porto opera em águas abrigadas pela barreira de recifes naturais que caracterizam o litoral sul pernambucano. Essa barreira, que também é responsável pelas famosas piscinas naturais de Porto de Galinhas, interage com as marés criando condições únicas de navegação que exigem conhecimento preciso dos horários de preamar e baixamar.`,

  'porto-de-maceio': `Maceió é a capital de Alagoas e um dos destinos de praia mais procurados do Brasil, famosa pelas piscinas naturais formadas pelos recifes de coral. As praias de Pajuçara, Ponta Verde e Jatiúca têm suas condições transformadas radicalmente pela maré: na maré baixa, surgem as icônicas piscinas coloridas, acessíveis de jangada, onde é possível enxergar o fundo do mar a olho nu. Os passeios de jangada às piscinas naturais de Maceió só são possíveis com a maré na altura certa — informação que o MaréAgora fornece com precisão para você planejar seu passeio.`,

  'terminal-maritimo-inacio-barbosa': `O Terminal Marítimo Inácio Barbosa, em Barra dos Coqueiros (SE), é o principal porto comercial de Sergipe, localizado na margem norte da foz do Rio Sergipe. O terminal movimenta principalmente combustíveis e granéis líquidos. A região da foz do Sergipe apresenta condições de maré características do litoral nordestino, com variações moderadas que influenciam a navegação de acesso ao terminal e as condições das praias do município, que vêm se desenvolvendo como destino turístico complementar a Aracaju.`,

  'capitania-dos-portos-de-sergipe': `Aracaju é a capital de Sergipe e uma cidade banhada pelo Rio Sergipe e pelo oceano Atlântico. As praias de Aracaju — Atalaia, Aruana e a orla do Mosqueiro — têm suas condições de banho influenciadas pelas marés do litoral sergipano. A maré baixa é o período preferido pelos banhistas locais, quando o mar recua e a faixa de areia se amplia consideravelmente. A capital sergipana é também ponto de partida para passeios pelos coqueirais e manguezais do litoral sul, cujas trilhas aquáticas dependem das condições de maré para acesso seguro.`,

  'arquipelago-de-fernando-de-noronha': `Fernando de Noronha é um arquipélago vulcânico localizado a 545 km do litoral nordestino e Patrimônio Natural da Humanidade pela UNESCO. As marés no arquipélago têm características oceânicas, com variações moderadas de cerca de 2 metros, mas seu impacto nas condições de mergulho e snorkeling é significativo. A famosa Baía dos Porcos, as Piscinas Naturais e a Praia do Sancho têm seus melhores momentos definidos pelos horários de maré baixa, quando a visibilidade subaquática é máxima e o acesso às formações rochosas é mais seguro.`,

  // ── Região Sudeste ────────────────────────────────────────────────────────

  'porto-de-madre-de-deus': `Madre de Deus é um município baiano localizado na Baía de Todos os Santos, famoso por abrigar o Terminal Aquaviário da Petrobras — o maior terminal de petróleo do Brasil. A Baía de Todos os Santos é o maior estuário do Brasil e apresenta dinâmica de maré complexa, com correntes intensas nos canais de navegação durante as trocas de maré. O conhecimento preciso dos horários de preamar e baixamar é fundamental para a operação segura de navios-tanque que acessam o terminal e para as embarcações de pesca artesanal que atuam nas águas da baía.`,

  'porto-de-aratu': `A Base Naval de Aratu e o Porto de Aratu estão localizados na Baía de Todos os Santos, um dos maiores e mais importantes corpos d'água costeiros do Brasil. A baía abriga dezenas de ilhas, comunidades pesqueiras tradicionais e um ecossistema de manguezal único. As marés na Baía de Todos os Santos têm amplitude moderada, em torno de 2 a 3 metros, mas as correntes geradas pelo movimento da maré nos canais entre as ilhas podem ser intensas e perigosas para embarcações de pequeno porte que navegam sem planejamento adequado.`,

  'porto-de-salvador': `Salvador é a capital da Bahia e uma das cidades mais ricas culturalmente do Brasil. A cidade está localizada em uma península na entrada da Baía de Todos os Santos, e suas praias — Barra, Ondina, Rio Vermelho e Itapoã — têm condições de banho influenciadas pelas marés do Atlântico Sul. O famoso Farol da Barra, ponto turístico icônico da cidade, está na confluência da Baía de Todos os Santos com o mar aberto, onde as correntes de maré são perceptíveis e devem ser consideradas por nadadores e praticantes de esportes aquáticos.`,

  'porto-de-ilheus': `Ilhéus é uma cidade baiana historicamente ligada à cultura do cacau e cenário do romance "Gabriela, Cravo e Canela" de Jorge Amado. O porto da cidade, localizado na foz do Rio Cachoeira, serve ao escoamento da produção agrícola regional e à pesca artesanal. As praias de Ilhéus — Praia do Sul, Marciano e Cururupe — têm beleza natural preservada e suas condições são influenciadas pelas marés do sul da Bahia. A maré baixa revela piscinas naturais entre as pedras e amplia as faixas de areia das praias, tornando-se o período preferido para caminhadas e mergulho com snorkel.`,

  'terminal-de-barra-do-riacho': `O Terminal de Barra do Riacho, em Aracruz (ES), é um importante porto privado do Espírito Santo, especializado na exportação de celulose produzida pelas fábricas da região. Localizado na costa norte capixaba, o terminal opera em águas expostas ao Atlântico Sul, com marés semidiurnas de amplitude moderada. A precisão no monitoramento das marés é importante para as operações de atracação e para a navegação de grandes navios cargueiros que acessam o terminal pela costa aberta.`,

  'porto-de-tubarao': `O Porto de Tubarão, em Vitória, é um dos maiores terminais de exportação de minério de ferro do mundo, operado pela Vale. Localizado na Baía de Vitória, o porto opera em ambiente de marés semidiurnas com amplitude entre 1 e 1,5 metros, típica do litoral capixaba. Apesar da amplitude relativamente moderada em comparação ao Norte e Nordeste, o monitoramento das marés é crítico para a operação de navios Capesize e Valemax que carregam centenas de milhares de toneladas de minério por viagem.`,

  'porto-de-vitoria': `Vitória é a capital do Espírito Santo e uma das poucas capitais brasileiras localizadas em uma ilha. A Baía de Vitória, que separa a ilha continental do município de Vila Velha, apresenta dinâmica de maré semidiurna com correntes perceptíveis nos canais de navegação durante as trocas. As praias capixabas — Camburi, Curva da Jurema e as praias de Vila Velha — têm condições de banho influenciadas pelas marés do litoral do ES. A maré baixa é o período preferido pelos pescadores de costão que praticam a pesca com vara nas pedras da orla.`,

  'ilha-da-trindade': `A Ilha da Trindade é um território brasileiro isolado no Atlântico Sul, localizada a mais de 1.100 km da costa do Espírito Santo. A ilha é administrada pela Marinha do Brasil e abriga uma importante estação científica. Por estar em pleno oceano, suas marés têm características oceânicas puras, com variações menores que as da costa continental. A ilha é um dos sítios de desova de tartarugas marinhas mais importantes do Atlântico Sul, e o monitoramento das marés é parte do trabalho dos pesquisadores que estudam a chegada das tartarugas à praia.`,

  'terminal-da-ponta-do-ubu-i': `O Terminal da Ponta do Ubu, em Anchieta (ES), é um porto privado especializado na exportação de ferro-nióbio e outros produtos metalúrgicos. Localizado na costa sul do Espírito Santo, o terminal opera em mar aberto com marés semidiurnas do litoral capixaba. Anchieta é também uma cidade histórica, berço do Padre José de Anchieta, e tem praias preservadas que atraem turistas e pescadores. As marés locais influenciam as condições de pesca na costa rochosa e nas praias de areia da região.`,

  'terminal-maritimo-de-imbetiba': `Macaé é a "capital do petróleo" brasileiro, sede das principais operações offshore da Petrobras na Bacia de Campos. O Terminal de Imbetiba, em Macaé, é um hub logístico crucial para o abastecimento de plataformas de petróleo. As marés no litoral norte fluminense têm amplitude moderada, mas o monitoramento constante é essencial para as operações de transfer de pessoal e carga entre o porto e as embarcações de apoio offshore. As praias de Macaé — Imbetiba, Cavaleiros e Praia Rasa — têm suas condições influenciadas pelas marés e pela ressurgência de águas frias típica da Bacia de Campos.`,

  'rio-de-janeiro-fiscal': `O Rio de Janeiro é a cidade mais famosa do Brasil e suas praias — Copacabana, Ipanema, Barra da Tijuca e Grumari — são ícones mundiais. As marés na Baía de Guanabara e no litoral oceânico carioca são semidiurnas, com amplitude entre 1 e 1,3 metros. Apesar da variação relativamente pequena, as marés influenciam significativamente as condições das praias: a maré baixa revela bancos de areia, facilita a pesca de costão e é o momento ideal para o surfe em algumas praias. A maré alta traz ondas mais próximas à orla e melhores condições para o bodyboard em Ipanema e Arpoador.`,

  'porto-de-itaguai': `Itaguaí abriga o Porto de Sepetiba, um dos maiores e mais modernos complexos portuários do Brasil, estrategicamente localizado na Baía de Sepetiba. O porto é especializado em contêineres, automóveis e minérios, e tem crescido rapidamente como alternativa ao congestionado Porto do Rio de Janeiro. A Baía de Sepetiba apresenta condições de maré semidiurna com correntes que devem ser monitoradas pelas embarcações que navegam nos canais de acesso ao porto.`,

  'porto-do-forno': `Arraial do Cabo, no Rio de Janeiro, é considerada o "Caribe Brasileiro" por suas águas cristalinas e tonalidades azul-turquesa únicas. O Porto do Forno serve às embarcações de pesca e turismo que operam na região. As correntes de maré em Arraial do Cabo são fortemente influenciadas pela ressurgência de águas frias que caracteriza a região — fenômeno que traz nutrientes da profundeza e é responsável pela extraordinária biodiversidade marinha local. A visibilidade subaquática, que pode chegar a 20 metros, varia conforme as condições de maré e a intensidade da ressurgência.`,

  'terminal-da-ilha-guaiba': `O Terminal da Ilha Guaíba, em Mangaratiba (RJ), é um porto privado especializado na exportação de minério de ferro. Localizado na Baía de Sepetiba, opera em um ambiente de marés semidiurnas com amplitude moderada. Mangaratiba é também um município turístico, com boa infraestrutura para esportes náuticos e acesso às ilhas da Baía da Ilha Grande — um dos destinos de ecoturismo mais preservados do estado do Rio de Janeiro, onde as condições de navegação e mergulho são fortemente influenciadas pelas marés locais.`,

  'porto-do-acu': `O Porto do Açu, em São João da Barra (RJ), é um dos maiores e mais modernos superportos da América Latina, com capacidade para receber navios de grande porte. Localizado no norte fluminense, o porto opera em mar aberto com marés semidiurnas do litoral do Rio de Janeiro. O complexo portuário do Açu é estratégico para o escoamento de petróleo da Bacia de Campos e para a importação de insumos industriais. O monitoramento preciso das marés é crítico para as operações de atracação e para a gestão dos canais de acesso ao porto.`,

  'porto-de-angra-dos-reis': `Angra dos Reis é um dos destinos turísticos mais sofisticados do Brasil, famosa por suas 365 ilhas, praias paradisíacas e pela proximidade com Ilha Grande — Patrimônio Natural da Humanidade. As marés na Baía da Ilha Grande são semidiurnas, com amplitude entre 1 e 1,2 metros, e influenciam diretamente as condições de navegação entre as ilhas e a qualidade das praias. As melhores condições para ancoragem nos enseadas protegidas, o acesso às praias de difícil chegada e as trilhas de acesso por mar dependem do planejamento dos horários de maré.`,

  'porto-de-sao-sebastiao': `São Sebastião, no litoral norte de São Paulo, é famosa pela travessia de balsa para Ilhabela — a maior ilha costeira do Brasil. O canal de São Sebastião, que separa o continente da ilha, apresenta correntes de maré perceptíveis que afetam a travessia de balsas e embarcações menores. Ilhabela, com suas mais de 80 praias, cachoeiras e trilhas, tem condições de banho e mergulho fortemente influenciadas pelas marés. O arquipélago é um dos melhores destinos de mergulho do Brasil, com naufrágios acessíveis que revelam sua melhor face na maré baixa e com boa visibilidade.`,

  'porto-de-santos': `Santos é a cidade com o maior porto da América Latina e uma das mais importantes cidades portuárias do mundo. O Porto de Santos movimenta cerca de 30% de toda a balança comercial brasileira. As marés em Santos são semidiurnas, com amplitude entre 1 e 1,5 metros, e influenciam diretamente as operações de atracação e a navegação no Canal de Santos. As praias da cidade — a mais longa orla urbana do mundo com 7 km — têm suas condições de banho afetadas pelas marés, com a maré baixa revelando maior extensão de areia e a maré cheia trazendo o mar mais próximo da orla histórica.`,

  // Litoral SP
  'guaruja': `O Guarujá é o destino de praia mais procurado pelos paulistanos, distante apenas 90 km da capital por rodovia. Com praias como Pitangueiras, Enseada, Perequê e Tombo, o município recebe milhões de turistas por ano, especialmente nos finais de semana e feriados. As marés do Guarujá são referenciadas pela estação de Santos e têm amplitude semidiurna de cerca de 1 a 1,5 metros. A maré baixa na Praia do Tombo cria condições ideais para o surfe, enquanto na Enseada e Pitangueiras a maré cheia é preferida pelos banhistas pela maior profundidade e menor exposição ao fundo rochoso.`,

  'sao-vicente': `São Vicente é considerada a cidade mais antiga do Brasil, fundada em 1532, e faz parte da Baixada Santista junto com Santos e Guarujá. Suas praias — Itararé, Milionários e Gonzaguinha — são opções populares e mais tranquilas que as de Santos. As marés em São Vicente são praticamente idênticas às de Santos, com amplitude semidiurna entre 1 e 1,5 metros. A orla de São Vicente tem características diferentes de Santos — com pedras e costões rochosos que ficam expostos na maré baixa, criando piscinas naturais e condições propícias para a pesca de costão.`,

  'praia-grande': `Praia Grande é o município paulista com a maior concentração de apartamentos por metro quadrado do Brasil, um destino massivo de verão para famílias do interior de São Paulo. Com uma orla de 22 km dividida em praias como Ocian, Caiçara, Aviação e Boqueirão, a cidade recebe milhões de turistas na alta temporada. As marés em Praia Grande têm uma pequena defasagem de cerca de 5 minutos em relação a Santos, com amplitude semidiurna similar. A maré baixa revela bancos de areia rasos ideais para crianças e facilita os passeios de pedalinho nas praias centrais.`,

  'bertioga': `Bertioga é um município do litoral norte de São Paulo, separado do Guarujá pelo Canal de Bertioga — um dos canais históricos mais importantes da colonização brasileira. As praias de Bertioga — como Riviera, Vista Linda e São Lourenço do Sul — são mais preservadas e menos movimentadas que as da Baixada Santista. As marés em Bertioga têm uma defasagem de cerca de 15 minutos em relação a Santos e influenciam diretamente as condições de navegação no canal histórico, frequentado por embarcações de pesca e lazer.`,

  'riviera-de-sao-lourenco': `A Riviera de São Lourenço é um dos condomínios residenciais de praia mais sofisticados do Brasil, com infraestrutura completa e praias organizadas. Localizada em Bertioga, no litoral norte paulista, a Riviera tem uma orla bem cuidada com estrutura de apoio para esportes aquáticos. As marés nessa região têm as mesmas características de Bertioga, com defasagem de 15 minutos em relação a Santos. A maré baixa na Riviera revela uma extensa faixa de areia que se estende até a foz do Rio São Lourenço, criando condições ideais para caminhadas e esportes de praia.`,

  'mongagua': `Mongaguá é um município da Baixada Santista conhecido como destino familiar e alternativa mais tranquila às praias de Santos e Praia Grande. Com praias como Agenor de Campos e Flórida, a cidade tem uma orla preservada com menos estrutura urbana e mais contato com a natureza. As marés em Mongaguá têm uma defasagem de cerca de 10 minutos em relação a Santos. A maré baixa em Mongaguá revela bancos de areia e permite longas caminhadas pela orla, enquanto a maré alta traz o mar mais próximo da vegetação costeira remanescente.`,

  'itanhaem': `Itanhaém é uma das cidades mais antigas de São Paulo e tem a maior extensão de praia do litoral sul paulista, com mais de 40 km de costa praticamente ininterrupta. A cidade é um destino de praia popular entre famílias que buscam mais tranquilidade e natureza preservada. As marés em Itanhaém têm uma defasagem de 15 minutos em relação a Santos, com amplitude semidiurna similar. A maré baixa em Itanhaém revela extensos bancos de areia e a foz dos rios que deságuam na praia, criando condições únicas para pesca de arremesso e passeios a pé.`,

  'peruibe': `Peruíbe é o município mais ao sul da Baixada Santista e um dos destinos de natureza mais preservados do litoral paulista, próximo à APA da Serra do Mar e ao Parque Estadual do Prelado. As praias de Peruíbe — como Praia do Centro, Barra do Una e Guarauzinho — têm características mais selvagens e são frequentadas por quem busca sossego e contato com a natureza. As marés em Peruíbe têm defasagem de 20 minutos em relação a Santos e amplitude semidiurna de cerca de 1 a 1,3 metros, influenciando o acesso às praias mais isoladas da região.`,

  // ── Região Sul ────────────────────────────────────────────────────────────

  'barra-de-paranagua-sueste': `A Barra de Paranaguá pelo Canal Sueste é uma das entradas marítimas mais movimentadas do sul do Brasil, utilizada por navios que acessam o Porto de Paranaguá pelo canal mais curto. A região da Barra é conhecida por suas correntes intensas durante as trocas de maré, especialmente nos períodos de sizígia, quando a diferença entre preamar e baixamar é máxima. Pilotos de barra e práticos que operam nessa região acumulam décadas de conhecimento sobre o comportamento das marés e correntes nos canais estuarinos da Baía de Paranaguá.`,

  'porto-de-paranagua': `Paranaguá abriga o maior porto exportador de grãos da América Latina e um dos maiores do mundo. O Porto de Paranaguá, localizado no estuário da Baía de Paranaguá, opera em condições de maré semidiurna com amplitude entre 1,5 e 2 metros. A variação de maré é fundamental para o gerenciamento do calado dos navios graneleiros que carregam soja, milho e outros grãos com margens de segurança mínimas. A baía também é um dos maiores estuários do sul do Brasil, com ecossistemas de manguezal preservados que dependem do ciclo das marés para sua saúde ecológica.`,

  'barra-de-paranagua-galheta': `O Canal da Galheta é o principal acesso marítimo ao Porto de Paranaguá, utilizado por navios de maior calado. Com profundidade maior que o Canal Sueste, a Galheta é preferida pelos navios graneleiros e tanqueiros que acessam os terminais do complexo portuário de Paranaguá. As correntes no canal são geradas principalmente pelo fluxo de maré e pela descarga dos rios que alimentam a Baía de Paranaguá, tornando o monitoramento preciso das marés indispensável para a navegação segura nesse trecho.`,

  'terminal-portuario-da-ponta-do-felix': `O Terminal Portuário da Ponta do Félix, em Antonina (PR), é um porto privado localizado no fundo da Baía de Paranaguá, especializado em granéis sólidos e líquidos. Por estar no extremo interior da baía, as marés em Antonina chegam com uma defasagem de aproximadamente 1 hora em relação à barra, e a amplitude é ligeiramente reduzida pelo efeito do percurso estuarino. A cidade de Antonina é uma das mais antigas do Paraná e tem um cais histórico que complementa a atividade portuária moderna do terminal privado.`,

  'porto-de-sao-francisco-do-sul': `São Francisco do Sul, em Santa Catarina, é o terceiro porto mais antigo do Brasil e o principal terminal graneleiro do estado. Localizado em uma ilha, o município tem um centro histórico bem preservado e um porto que movimenta grandes volumes de grãos, fertilizantes e automóveis. As marés no Canal do Linguado, que separa a ilha do continente, são semidiurnas com amplitude entre 0,8 e 1,2 metros. As praias da ilha — Ubatuba, Prainha e Paulas — têm suas condições de banho e pesca influenciadas pelas marés do litoral norte catarinense.`,

  'porto-de-itajai': `Itajaí é um dos maiores portos de contêineres da América do Sul e o principal porto de Santa Catarina. Localizado na foz do Rio Itajaí-Açu, o porto opera em ambiente de marés semidiurnas com amplitude entre 0,8 e 1,2 metros, mas com correntes significativas geradas pelo fluxo do rio — especialmente em períodos de chuva intensa no Vale do Itajaí. A cidade de Itajaí e as vizinhas Balneário Camboriú e Navegantes têm suas praias influenciadas pelas marés do litoral central catarinense, com a maré baixa revelando extensas faixas de areia.`,

  'porto-de-florianopolis': `Florianópolis é a capital de Santa Catarina e um dos destinos de praia mais procurados do Brasil, famosa por suas mais de 100 praias distribuídas em uma ilha e numa pequena porção continental. As marés em Florianópolis são semidiurnas, com amplitude entre 0,5 e 1 metro — menor que no norte e nordeste, mas com impacto significativo nas condições de praias como Joaquina, Mole, Barra da Lagoa e Campeche. A Lagoa da Conceição, conectada ao mar, tem seu nível influenciado pelas marés através do canal da Barra da Lagoa, criando correntes que são aproveitadas pelos praticantes de windsurf e kitesurf.`,

  'porto-de-imbituba': `Imbituba é um município catarinense que combina atividade portuária com turismo de natureza. A cidade é um dos principais pontos de observação de baleias-francas do Brasil — os cetáceos chegam à costa entre junho e novembro para se reproduzir nas águas mais quentes do litoral sul. As marés em Imbituba são semidiurnas com amplitude moderada, e as baleias utilizam as enseadas protegidas durante os períodos de maré mais calma para amamentação dos filhotes. O porto de Imbituba movimenta principalmente cerâmica e produtos regionais.`,

  'porto-do-rio-grande': `Rio Grande, no extremo sul do Brasil, abriga o único porto marítimo do Rio Grande do Sul e uma das cidades mais frias do litoral brasileiro. Localizado na entrada da Lagoa dos Patos — a maior laguna da América do Sul —, o porto opera em condições únicas de maré influenciadas tanto pelo Atlântico Sul quanto pela dinâmica da laguna. As correntes na barra de Rio Grande podem ser intensas e imprevisíveis, combinando o efeito das marés com os ventos predominantes do sul e o volume d'água da Lagoa dos Patos.`,

  'base-comandante-ferraz': `A Base Antártica Comandante Ferraz, localizada na Baía do Almirantado na Ilha Rei George, é a estação científica brasileira na Antártida. As marés na Antártida têm características únicas, com componentes complexas resultantes da geometria do oceano Austral. A amplitude varia conforme a localização, mas o monitoramento preciso é fundamental para as operações logísticas da base — especialmente o desembarque de materiais e combustível por barcaças, que dependem de condições específicas de maré e de mar para segurança da operação.`,

};

/**
 * Retorna a descrição única do porto pelo slug.
 * Se não encontrar, retorna string vazia para manter compatibilidade.
 */
export function getPortoDescription(slug: string): string {
  return portoDescriptions[slug] ?? '';
}

export default portoDescriptions;
