/**
 * MaréAgora — Descrições únicas por porto para SEO on-page
 * Cada texto é específico para aquela localidade, evitando conteúdo duplicado.
 * Uso: importe getPortoDescription(slug) e passe para PortPageContent.
 */

const portoDescriptions: Record<string, string> = {

  // ── Região Norte ──────────────────────────────────────────────────────────

  'porto-de-belem': `Belém do Pará é uma das cidades brasileiras com maior amplitude de maré do mundo. Localizada na foz do Rio Pará, próxima à confluência com o Rio Amazonas, as marés chegam a variar mais de 4 metros entre a preamar e a baixamar em períodos de sizígia. Esse fenômeno, chamado localmente de "pororoca" nas regiões mais internas, influencia diretamente a rotina portuária, a pesca artesanal e a navegação fluvial. O porto de Val de Cães é o principal terminal de passageiros e cargas da região Norte, e o conhecimento das marés é essencial para a operação segura de embarcações no canal do estuário.\n\nAs operações pesqueiras e de transporte fluvial no estuário do rio Guamá e na baía do Guajará são ditadas pelo ritmo das marés. Embarcações regionais aguardam o estofo da preamar para navegar com segurança e economizar combustível ao subir os rios da bacia. Devido à proximidade com a Ilha do Marajó, a maré vazante cria correntes fortes que exigem perícia dos barqueiros. Como referência principal do norte, as tábuas de Belém são vitais para evitar encalhes nos extensos bancos de areia formados pelos sedimentos amazônicos.`,

  'ilha-do-mosqueiro': `A Ilha do Mosqueiro, localizada a cerca de 70 km de Belém, é um destino de praia muito frequentado pelos paraenses, especialmente nos finais de semana. Por estar inserida no estuário amazônico, suas marés são influenciadas tanto pelo ciclo lunar quanto pela descarga dos grandes rios da bacia amazônica. As praias de água doce da ilha — como Praia do Paraíso e Praia Grande — têm suas condições de banho diretamente afetadas pelos horários de maré, sendo a maré cheia o período preferido pelos banhistas locais.\n\nAs praias de água doce do rio Pará sofrem transformações drásticas conforme a maré oscila, influenciando fortemente o turismo local. Durante a preamar, as ondas se formam e garantem banhos refrescantes em praias como o Farol e o Chapéu Virado. Já na baixamar, a longa faixa de lama e areia afasta a água por dezenas de metros, dificultando o mergulho. Por estar no interior do estuário, Mosqueiro tem um pequeno atraso em relação à referência de Belém, mas preserva a mesma dinâmica extrema.`,

  'porto-de-vila-do-conde': `O Porto de Vila do Conde, em Barcarena (PA), é um dos terminais portuários mais movimentados da região Norte, responsável pelo escoamento de alumínio, caulim e outros minérios. Localizado no estuário do Rio Pará, o porto opera em um ambiente de marés com amplitudes elevadas, exigindo planejamento rigoroso das operações de atracação e desatracação. A variação da maré nessa região pode ultrapassar 3,5 metros, tornando o acompanhamento da tábua de marés indispensável para pilotos e práticos locais.\n\nSituado na baía de Marajó, o terminal portuário tem sua rotina de exportação de minérios moldada pelas impressionantes amplitudes estuarinas. Pilotos precisam sincronizar a aproximação de navios de grande porte com a preamar para assegurar um calado adequado nos canais de acesso. As correntes de maré, que se intensificam fortemente nas sizígias, afetam diretamente a atracação. Além do setor industrial, a pesca artesanal barcarenenese depende das correntes de vazante para o posicionamento estratégico das redes e currais nas margens do estuário.`,

  'atracadouro-de-breves': `Breves é um município do arquipélago do Marajó, no coração do estuário amazônico. O atracadouro local é ponto de passagem obrigatório para embarcações que navegam pelos furos e igarapés da região. As marés em Breves são influenciadas pelos ciclos lunares e pela enorme massa d'água dos rios Amazonas e Pará, resultando em variações significativas que chegam a afetar o nível dos igarapés por quilômetros adentro. Pescadores e ribeirinhos da região dependem do horário das marés para suas atividades diárias de subsistência.\n\nA navegação pelos labirínticos furos do arquipélago do Marajó depende essencialmente da variação do nível das águas. Embarcações que transportam madeira e açaí usam a maré enchente para adentrar canais rasos que secam completamente na baixamar. Geograficamente localizado no coração dos estreitos amazônicos, Breves experimenta fortes correntes de maré impulsionadas pelo encontro entre as águas fluviais e a força oceânica, tornando o monitoramento do ciclo um conhecimento de sobrevivência e eficiência logística para a população ribeirinha da região.`,

  'porto-de-santana': `O Porto de Santana, no Amapá, é o principal terminal portuário do estado e porta de entrada para o escoamento de minérios extraídos na região de Serra do Navio. Situado às margens do Rio Amazonas, próximo à sua foz norte, o porto é diretamente impactado pelas marés oceânicas que penetram rio adentro. A amplitude das marés em Santana é considerável, com variações que podem chegar a 3 metros, exigindo atenção constante dos operadores portuários e das embarcações que acessam o terminal.\n\nO escoamento das riquezas minerais pelo rio Amazonas exige um alinhamento rigoroso com o fluxo das marés no canal do norte. Navios de longo curso dependem das preamares para navegar com calado máximo sem o risco de tocar nos bancos de areia móveis que caracterizam o fundo do rio. Diferente da foz principal, Santana possui uma dinâmica mista onde o imenso volume de água fluvial amortece ligeiramente a influência oceânica, gerando correntes de vazante significativamente mais velozes e duradouras que as de enchente.`,

  'igarape-grande-do-curua': `O Igarapé Grande do Curuá, localizado no litoral norte do Pará, próximo à foz do Rio Amazonas, é uma região de intensa atividade pesqueira artesanal. As marés nessa área são fortemente influenciadas pela dinâmica estuarina amazônica, com variações bruscas de nível que ocorrem duas vezes ao dia. Pescadores locais utilizam o conhecimento tradicional das marés para definir os melhores horários de lançamento de redes e armadilhas, especialmente durante os períodos de maré vazante, quando os peixes se concentram nas áreas mais rasas.\n\nO modo de vida das comunidades ribeirinhas no arquipélago do Marajó é pautado pela subida e descida das águas nos igarapés. A pesca de subsistência é mais farta durante os curtos períodos de estofo, quando as correntes perdem força. A geografia fragmentada do estuário faz com que o fluxo da maré se acelere ao passar pelos canais estreitos, formando rebojos traiçoeiros. O planejamento diário, desde a coleta de caranguejos no manguezal até o deslocamento para o centro urbano, é inteiramente sincronizado com a tábua.`,

  'barra-norte-arco-lamoso': `A Barra Norte do Rio Amazonas, no trecho conhecido como Arco Lamoso, é uma região de navegação complexa e sensível às variações de maré. A encontro das águas do Atlântico com a descarga do maior rio do mundo cria condições únicas de corrente e nível d'água, exigindo precisão no planejamento das rotas de navegação. A tábua de marés desse ponto é referência fundamental para embarcações que cruzam a foz norte do Amazonas, incluindo navios de grande porte e embarcações pesqueiras oceânicas.\n\nA gigantesca área de transição entre o rio Amazonas e o Oceano Atlântico apresenta uma batimetria extremamente instável que muda com as correntes de maré. A navegação comercial de grande porte utiliza a enchente para superar os pontos mais rasos do arco, maximizando a carga transportada. A presença de uma extensa plataforma de lama fluviomarinha faz com que a maré interaja de forma peculiar, dissipando a energia das ondas e criando um ambiente onde a leitura precisa da tábua previne encalhes desastrosos no lodo.`,

  'fundeadouro-de-salinopolis': `Salinópolis é o principal destino de praia do nordeste paraense, famosa pelas praias do Atalaia e Corvina. Localizada em uma região de transição entre o estuário amazônico e o litoral aberto, Salinópolis apresenta marés com amplitude moderada a elevada, com variações que influenciam diretamente as condições das praias. Na maré baixa, surgem extensas faixas de areia e piscinas naturais muito procuradas por turistas e famílias locais. O horário das marés é informação essencial para quem planeja visitar as praias da região.\n\nO turismo balnear na famosa praia do Atalaia tem as marés como principal atração e desafio. O amplo declive da praia permite que carros transitem pela areia, mas as marés de sizígia avançam rapidamente, surpreendendo motoristas desavisados e submergindo veículos todos os anos. A maré enchente cria ondas muito apreciadas pelos surfistas locais, enquanto a baixamar permite passeios tranquilos pelas lagoas temporárias formadas nas irregularidades da costa. Diferentemente dos portos fluviais, Salinas recebe a força bruta da maré oceânica do Atlântico equatorial.`,

  'ilha-dos-guaras': `A Ilha dos Guarás, no litoral paraense, é uma área de preservação ambiental importante, com manguezais densos e grande biodiversidade costeira. A região é conhecida pelo avistamento de guarás-vermelhos, aves migratórias que habitam os manguezais. As marés nessa ilha têm amplitude elevada, inundando e expondo periodicamente grandes extensões de manguezal, o que cria um ciclo vital para a fauna local — caranguejos, peixes e aves que dependem desse ritmo para alimentação e reprodução.\n\nO ecoturismo e a pesca artesanal nos densos manguezais dependem vitalmente da oscilação do nível do mar. A observação da revoada dos guarás-vermelhos é mais acessível na maré alta, quando pequenas embarcações conseguem adentrar os furos e igarapés mais protegidos. Por outro lado, a catação de caranguejos, sustento de muitas famílias, só pode ser realizada na baixamar extrema. A geografia isolada e as margens lodosas fazem com que a compreensão das marés seja essencial para evitar que pescadores e turistas fiquem presos na lama.`,

  // ── Região Nordeste ───────────────────────────────────────────────────────

  'porto-de-itaqui': `O Porto do Itaqui, em São Luís do Maranhão, é um dos portos mais importantes do Brasil e o de maior profundidade natural do país. Sua localização no Golfão Maranhense o coloca em uma das regiões de maior amplitude de maré do Brasil, com variações que podem superar 6 metros durante as marés de sizígia — um fenômeno raro em escala mundial. Essa característica torna o planejamento das marés absolutamente crítico para a operação de navios graneleiros, de contêineres e de combustíveis que movimentam bilhões de reais em carga anualmente.\n\nA impressionante amplitude macrotidal do litoral maranhense transforma o cenário costeiro e portuário a cada seis horas. Para os navios do tipo Capesize, que figuram entre os maiores do mundo, o acesso seguro aos berços de atracação é possível apenas nos curtos intervalos da preamar. As correntes geradas pelo intenso fluxo de água na baía de São Marcos exigem rebocadores de altíssima potência. Esta característica geográfica extrema faz do terminal o laboratório perfeito para manobras de precisão, diferenciando sua operação de qualquer outro porto brasileiro.`,

  'sao-luis': `São Luís do Maranhão está situada em uma ilha banhada pelo Golfão Maranhense, uma das regiões com maior amplitude de maré do mundo. As praias da cidade — como Calhau, Ponta d'Areia e Araçagi — têm suas condições radicalmente transformadas pelo ciclo das marés: na maré baixa, surgem quilômetros de bancos de areia e piscinas naturais; na maré alta, o mar avança até a orla. Essa dinâmica extrema é parte da identidade cultural e turística de São Luís, e conhecer os horários das marés é essencial para aproveitar ao máximo as praias da capital maranhense.\n\nA dinâmica balnear da capital maranhense é governada pelas marés extremas, alterando profundamente a paisagem das praias urbanas. Na maré baixa, praias como São Marcos e Calhau expõem bancos de areia e pedras por centenas de metros, perfeitos para longas caminhadas e esportes na areia. Contudo, quando o ciclo atinge a preamar nas sizígias, as ondas castigam fortemente os muros de contenção da orla. Esse movimento macrotidal também afeta a pesca costeira e o turismo náutico no Golfão Maranhense.`,

  'porto-de-tutoia': `Tutóia é um município maranhense localizado na foz do Rio Parnaíba, na divisa com o Piauí, e ponto de acesso aos Lençóis Maranhenses pelo lado leste. As marés na região de Tutóia são influenciadas tanto pelo oceano Atlântico quanto pela dinâmica do Delta do Parnaíba, um dos maiores deltas em mar aberto do mundo. A variação das marés afeta diretamente a navegação pelos canais do delta e o acesso às comunidades ribeirinhas que dependem de embarcações para transporte e pesca.\n\nPorta de entrada para o Delta das Américas, a navegação de turismo e a pesca dependem intrinsecamente das oscilações do nível do mar. Os barcos que levam visitantes para observar guarás e dunas navegam por labirintos de igarapés que secam rapidamente na maré vazante. Por estar na foz do Rio Parnaíba, a dinâmica hídrica mescla o regime oceânico com o volume de água doce, criando correntes complexas nas barras. O conhecimento da tábua é a única garantia de um retorno seguro para os piloteiros.`,

  'terminal-da-ponta-da-madeira': `O Terminal Marítimo da Ponta da Madeira, operado pela Vale em São Luís, é o maior terminal de exportação de minério de ferro do mundo. Localizado no Golfão Maranhense, onde as marés atingem amplitudes excepcionais de até 7 metros, o terminal opera com janelas de atracação rigorosamente controladas pelos horários de preamar e baixamar. Navios do tipo Valemax, os maiores graneleiros do mundo, dependem das condições de maré para acessar com segurança o canal de navegação do porto.\n\nA operação dos megagravineiros Valemax é ditada minuto a minuto pelo ciclo macrotidal extremo do Maranhão. O calado monumental dessas embarcações obriga a atracação estritamente durante o estofo da preamar, evitando as severas correntes de maré que cruzam o canal de aproximação. A geografia do Golfão Maranhense amplifica a elevação das águas, fornecendo profundidade extra gratuita que viabiliza recordes mundiais de carregamento de minério de ferro. O planejamento logístico portuário é subordinado às tabelas de previsão hidrodinâmica fornecidas pelas autoridades marítimas.`,

  'terminal-da-alumar': `O Terminal da Alumar, também em São Luís, é parte do complexo industrial do Consórcio de Alumínio do Maranhão. Assim como os demais terminais do Golfão Maranhense, opera em condições de maré extremas, com variações que exigem planejamento preciso para as operações de carregamento e descarregamento de bauxita e alumina. A amplitude das marés nessa região é uma das maiores da costa brasileira, tornando a tábua de marés um documento operacional crítico para toda a cadeia logística do alumínio.\n\nLocalizado no complexo estuarino de São Luís, o terminal lida com correntes bidirecionais de extrema força devido às enormes amplitudes de maré. Navios que descarregam matéria-prima para a indústria do alumínio precisam manobrar em canais de acesso onde bancos de areia móveis são constantemente redesenhados pelo fluxo intenso de preamar e baixamar. A operação exige monitoramento ininterrupto, pois o atraso de poucos minutos na desatracação pode significar que a embarcação fique presa no leito do estuário, comprometendo toda a cadeia de produção.`,

  'porto-de-luis-correia': `Luís Correia é um município piauiense com belas praias e o único litoral do estado. O porto local serve principalmente à pesca artesanal e ao pequeno escoamento de produção regional. As marés na costa do Piauí têm características do litoral nordestino, com variações moderadas e duas preamares e duas baixamares por dia. As praias de Luís Correia, como Atalaia e Coqueiro, têm suas melhores condições de banho nas horas próximas à preamar, quando o mar cobre as áreas rasas e a água fica mais limpa.\n\nNo curto litoral piauiense, a maré dita o ritmo da vibrante pesca costeira e do turismo em praias badaladas como o Coqueiro e Macapá. Os praticantes de kitesurf e windsurf aproveitam as correntes de maré enchente aliadas aos ventos alísios constantes para potencializar as manobras. A geografia da foz do rio Igaraçu forma estuários que, durante a baixamar, viram enormes piscinas rasas e bancos de areia, tornando-se atrações perfeitas para famílias e banhistas, enquanto a pesca embarcada prefere as águas mais profundas da preamar.`,

  'terminal-portuario-do-pecem': `O Terminal Portuário do Pecém, no Ceará, é um porto de águas profundas construído em mar aberto, diferente da maioria dos portos brasileiros instalados em baías protegidas. Por essa razão, suas operações são diretamente impactadas pelas condições de mar e pelas variações de maré do litoral cearense. O porto movimenta cargas diversas, incluindo combustíveis, contêineres e produtos siderúrgicos da Companhia Siderúrgica do Pecém. O acompanhamento das marés é especialmente importante para a navegação de aproximação, que ocorre em canal exposto ao mar aberto.\n\nConstruído como um moderno porto offshore afastado da linha de costa cearense, sua operação difere radicalmente dos portos estuarinos. Embora as marés semidiurnas locais apresentem amplitudes moderadas, os navios atracam diretamente em píeres expostos às correntes marítimas e aos fortes ventos alísios. A variação da tábua afeta principalmente o balanço das embarcações nos berços e o calado dinâmico durante a navegação no canal aberto. Além da indústria siderúrgica, a região adjacente abriga pontos excelentes de surf que reagem fortemente à transição da maré.`,

  'porto-de-mucuripe-fortaleza': `Fortaleza é a capital do Ceará e um dos destinos turísticos mais visitados do Brasil. O Porto do Mucuripe, localizado próximo ao centro da cidade, é referência de maré para todo o litoral cearense. As praias urbanas de Fortaleza — Iracema, Meireles e Futuro — têm suas condições influenciadas pelo ciclo das marés, com a maré baixa revelando piscinas naturais e a maré alta trazendo o mar até a orla. A cidade também é ponto de partida para passeios de buggy nas dunas do litoral leste e oeste, cujas melhores condições coincidem com determinados horários de maré.\n\nA tradicional pesca de lagosta e os famosos passeios de jangada nas praias de Fortaleza têm seu cronograma atrelado à oscilação das marés. Durante a baixamar, as jangadas turísticas encontram águas calmas para navegar até as formações rochosas próximas à orla, enquanto a preamar favorece a aproximação de pequenas embarcações pesqueiras na enseada do Mucuripe. A enseada artificialmente protegida funciona como um refúgio importante, e o porto serve como a referência absoluta para calcular as atividades marítimas e recreativas em todo o litoral cearense.`,

  'porto-de-areia-branca-termisa': `Areia Branca, no Rio Grande do Norte, é conhecida como a "capital do sal" — a região é responsável por grande parte da produção de sal marinho do Brasil. O porto local, operado pela Termisa, escoa a produção salineira da região. As marés no litoral potiguar são do tipo semidiurno, com duas preamares e duas baixamares diárias. As salinas da região dependem das condições de maré para o controle do nível d'água nas estruturas de evaporação, tornando a previsão de marés uma ferramenta de gestão produtiva para a indústria salineira local.\n\nA extração de sal, pilar econômico da região, depende do engenhoso aproveitamento das marés oceânicas do Rio Grande do Norte. A preamar conduz a água do mar pelos canais estuarinos do rio Mossoró até os imensos tanques de evaporação das salinas. O terminal offshore, construído em ilha artificial, opera com marés semidiurnas regulares, mas lida com o desafio de atracar navios saliníferos em mar aberto. As balsas que transportam o sal desde o continente até o porto-ilha organizam suas viagens com base no ciclo das águas.`,

  'porto-de-guamare': `Guamaré é um município do Rio Grande do Norte de grande importância para a indústria petrolífera brasileira — a região concentra campos de exploração de petróleo e gás da Petrobras. O porto local serve ao escoamento de produção e ao abastecimento das plataformas offshore. As marés no litoral de Guamaré têm variação moderada, típica do litoral nordestino, mas são monitoradas continuamente pelas operações offshore que dependem de condições seguras para transferência de pessoal e carga entre embarcações e plataformas.\n\nO suporte logístico vital para a indústria petrolífera e a pesca de crustáceos dependem da navegação em seus sinuosos canais de mangue. As embarcações de apoio offshore que cruzam a foz do estuário rumo às plataformas necessitam de calado seguro que apenas a maré cheia proporciona. A peculiaridade de possuir extensos recifes de arenito paralelos à costa faz com que a maré vazante forme piscinas naturais e retenha nutrientes, criando um ambiente altamente produtivo para os pescadores locais nas horas próximas da baixamar.`,

  'porto-de-macau': `Macau, no Rio Grande do Norte, é outro município inserido na região salineira do nordeste brasileiro, com importantes salinas e uma ativa frota pesqueira. O porto de Macau é ponto de referência para pescadores que atuam na costa potiguar e na plataforma continental. A lagosta é um dos principais produtos da pesca local, e as embarcações lobeiras utilizam os ciclos de maré e lua para planejar suas saídas ao mar. A maré baixa também é o período ideal para a coleta de mariscos e crustáceos nas áreas de manguezal próximas ao porto.\n\nNo centro da Costa Branca potiguar, a vida gira em torno das salinas, da pesca artesanal e dos grandes viveiros de camarão que dependem do estuário. A maré alta é essencial para a renovação da água dos viveiros e para a entrada das embarcações pesqueiras pelos canais que se abrem no complexo sistema de manguezais. Por outro lado, a maré baixa expõe vastas coroas de lama, período em que marisqueiras realizam a coleta manual de ostras e siriris, uma tradição cultural moldada pelo ritmo hidrológico diário.`,

  'porto-de-natal': `Natal é a capital do Rio Grande do Norte e um dos principais destinos turísticos do Nordeste brasileiro. O Porto de Natal, localizado no Rio Potengi, serve tanto ao tráfego comercial quanto à pesca. As praias de Natal — Ponta Negra, Areia Preta e as praias do litoral sul — têm condições fortemente influenciadas pelas marés. Os famosos passeios de buggy e jangada nas praias de Genipabu e Maracajaú têm seus melhores momentos definidos pelos horários de maré baixa, quando surgem as piscinas naturais e os recifes ficam expostos.\n\nNo estuário do rio Potengi, os horários das marés comandam a saída das escunas de turismo e das pequenas frotas pesqueiras. O turismo náutico, que explora os recifes formadores das piscinas naturais nas praias da orla, depende absolutamente da baixamar para garantir um banho seguro e uma ótima visibilidade. A geografia com falésias e recifes faz com que as ressacas coincidam perigosamente com as marés de sizígia, erodindo faixas de areia em praias urbanas icônicas como Ponta Negra e Areia Preta.`,

  'porto-de-cabedelo': `Cabedelo, na Paraíba, é o município mais ao norte do estado e abriga um dos portos mais tradicionais do Nordeste. Localizado na foz do Rio Paraíba, o porto é referência de maré para o litoral paraibano. A cidade é ponto de partida para passeios de catamarã ao litoral norte da Paraíba, incluindo a famosa Praia de Tambaba e o Cabo Branco — o ponto mais oriental das Américas. As condições de navegação na foz do Rio Paraíba são diretamente afetadas pelas marés, especialmente durante as sizígias, quando a corrente de vazante pode ser intensa.\n\nO estuário do rio Paraíba abriga intensas atividades portuárias, passeios turísticos ao pôr do sol e uma tradicional pesca artesanal. As fortes correntes vazantes no canal de acesso, geradas pela grande capacidade de retenção de água do manguezal, demandam atenção redobrada dos pilotos de navios e comandantes de lanchas. Diferente das praias oceânicas próximas, a variação da maré no porto dita as janelas de atracação de cargueiros e influencia diretamente as condições para a prática do stand up paddle e navegação recreativa até a Ilha da Restinga.`,

  'porto-do-recife': `Recife é a capital de Pernambuco e uma das maiores metrópoles do Nordeste. O Porto do Recife, um dos mais antigos do Brasil, está localizado na embocadura do Rio Capibaribe. As praias do litoral pernambucano — Boa Viagem, Porto de Galinhas e Muro Alto — são famosas pelos recifes de coral que formam piscinas naturais na maré baixa, atraindo milhares de turistas por ano. O controle da maré é fundamental nesses destinos: na maré alta, os recifes ficam submersos e as piscinas somem; na maré baixa, o espetáculo dos peixes coloridos entre as rochas é o principal atrativo.\n\nA proteção natural garantida pela famosa barreira de recifes define não apenas o nome da cidade, mas a maneira como o mar reage. Na baixamar, os recifes emergem, formando piscinas naturais extremamente calmas nas praias da zona sul, o que impulsiona fortemente o turismo balnear. Entretanto, com a elevação da preamar, as ondas ultrapassam a barreira rochosa, alterando bruscamente a agitação na orla. A referência do histórico porto situado na bacia dos rios Capibaribe e Beberibe guia todas as atividades costeiras da capital pernambucana.`,

  'porto-de-suape': `O Porto de Suape, em Ipojuca (PE), é um dos portos mais modernos e estratégicos do Brasil, com um complexo industrial que inclui refinaria, estaleiro e diversas indústrias. Localizado a 40 km ao sul do Recife, o porto opera em águas abrigadas pela barreira de recifes naturais que caracterizam o litoral sul pernambucano. Essa barreira, que também é responsável pelas famosas piscinas naturais de Porto de Galinhas, interage com as marés criando condições únicas de navegação que exigem conhecimento preciso dos horários de preamar e baixamar.\n\nAlojado atrás de imensos recifes de arenito, o complexo industrial exige manobras precisas das enormes embarcações comerciais entre os canais dragados. Apesar das marés semidiurnas moderadas do litoral sul pernambucano, as correntes geradas pela troca de massas d'água entre o mar aberto e as bacias portuárias internas são consideráveis. Para a comunidade local da vizinha Vila de Nazaré e os banhistas de praias próximas como Muro Alto, a maré baixa significa o acesso a longos passeios pelas bancadas de corais expostas.`,

  'porto-de-maceio': `Maceió é a capital de Alagoas e um dos destinos de praia mais procurados do Brasil, famosa pelas piscinas naturais formadas pelos recifes de coral. As praias de Pajuçara, Ponta Verde e Jatiúca têm suas condições transformadas radicalmente pela maré: na maré baixa, surgem as icônicas piscinas coloridas, acessíveis de jangada, onde é possível enxergar o fundo do mar a olho nu. Os passeios de jangada às piscinas naturais de Maceió só são possíveis com a maré na altura certa — informação que o MaréAgora fornece com precisão para você planejar seu passeio.\n\nO cartão postal da capital alagoana é pautado pelo relógio das marés oceânicas. O turismo nas emblemáticas piscinas naturais de Pajuçara ocorre unicamente nos momentos de baixamar, quando o nível da água despenca e permite que as jangadas ancorem com segurança nos corais. O porto comercial, situado no bairro de Jaraguá, convive com a forte atração turística e a pesca litorânea, fornecendo os horários essenciais para que os saveiros e escunas organizem suas rotas para as praias do Francês e Paripueira sem o risco de encalhe.`,

  'terminal-maritimo-inacio-barbosa': `O Terminal Marítimo Inácio Barbosa, em Barra dos Coqueiros (SE), é o principal porto comercial de Sergipe, localizado na margem norte da foz do Rio Sergipe. O terminal movimenta principalmente combustíveis e granéis líquidos. A região da foz do Sergipe apresenta condições de maré características do litoral nordestino, com variações moderadas que influenciam a navegação de acesso ao terminal e as condições das praias do município, que vêm se desenvolvendo como destino turístico complementar a Aracaju.\n\nResponsável pelo escoamento logístico sergipano, as operações atracam em píeres que sofrem a ação direta de correntes longitudinais na foz do rio Sergipe. A navegação de apoio offshore e os pesqueiros precisam harmonizar suas travessias da barra com a maré enchente para evitar as perigosas ondas que quebram nos bancos de areia durante a vazante. A variação estuarina tem papel crucial no transporte hidroviário entre Aracaju e a Barra dos Coqueiros, influenciando o dia a dia de moradores e turistas que exploram a região costeira.`,

  'capitania-dos-portos-de-sergipe': `Aracaju é a capital de Sergipe e uma cidade banhada pelo Rio Sergipe e pelo oceano Atlântico. As praias de Aracaju — Atalaia, Aruana e a orla do Mosqueiro — têm suas condições de banho influenciadas pelas marés do litoral sergipano. A maré baixa é o período preferido pelos banhistas locais, quando o mar recua e a faixa de areia se amplia consideravelmente. A capital sergipana é também ponto de partida para passeios pelos coqueirais e manguezais do litoral sul, cujas trilhas aquáticas dependem das condições de maré para acesso seguro.\n\nAs praias de águas turvas e mornas da capital sergipana recebem a forte influência da foz de importantes rios como o Sergipe e o Vaza-Barris. O banho de mar em praias extensas, como a Atalaia, é extremamente prazeroso durante a maré baixa, quando formam-se lagoas e a faixa de areia endurecida convida à prática de esportes. Para os pescadores do histórico bairro Industrial, acompanhar a tábua de marés da capitania é a regra fundamental para decidir o instante exato de lançar as redes no rio.`,

  'arquipelago-de-fernando-de-noronha': `Fernando de Noronha é um arquipélago vulcânico localizado a 545 km do litoral nordestino e Patrimônio Natural da Humanidade pela UNESCO. As marés no arquipélago têm características oceânicas, com variações moderadas de cerca de 2 metros, mas seu impacto nas condições de mergulho e snorkeling é significativo. A famosa Baía dos Porcos, as Piscinas Naturais e a Praia do Sancho têm seus melhores momentos definidos pelos horários de maré baixa, quando a visibilidade subaquática é máxima e o acesso às formações rochosas é mais seguro.\n\nIsolado no meio do Atlântico equatorial, o turismo ecológico no arquipélago está submetido aos rigores da dinâmica oceânica pura. Atividades famosas como o mergulho autônomo na Baía dos Porcos e a observação de vida marinha nas piscinas naturais do Atalaia dependem do estofo da maré baixa para oferecerem visibilidade cristalina e segurança aos visitantes. Embora não sofra influência fluvial, a topografia vulcânica acidentada provoca repuxos e ondas intensas na preamar, exigindo atenção redobrada de quem se aventura de barco em direção às praias de mar de fora.`,

  // ── Região Sudeste ────────────────────────────────────────────────────────

  'porto-de-madre-de-deus': `Madre de Deus é um município baiano localizado na Baía de Todos os Santos, famoso por abrigar o Terminal Aquaviário da Petrobras — o maior terminal de petróleo do Brasil. A Baía de Todos os Santos é o maior estuário do Brasil e apresenta dinâmica de maré complexa, com correntes intensas nos canais de navegação durante as trocas de maré. O conhecimento preciso dos horários de preamar e baixamar é fundamental para a operação segura de navios-tanque que acessam o terminal e para as embarcações de pesca artesanal que atuam nas águas da baía.\n\nA operação de grandes navios tanqueiros com derivados de petróleo depende completamente das marés que fluem pela Baía de Todos os Santos. As correntes bidirecionais formadas entre as dezenas de ilhas tornam-se extremamente fortes nas vazantes de sizígia. Pescadores artesanais da região utilizam esse fluxo contínuo de água para posicionar suas armadilhas ao longo dos canais estreitos, onde cardumes se deslocam com a maré. Sendo um terminal interno, Madre de Deus possui um ligeiro atraso temporal na preamar se comparado com o mar aberto de Salvador.`,

  'porto-de-aratu': `A Base Naval de Aratu e o Porto de Aratu estão localizados na Baía de Todos os Santos, um dos maiores e mais importantes corpos d'água costeiros do Brasil. A baía abriga dezenas de ilhas, comunidades pesqueiras tradicionais e um ecossistema de manguezal único. As marés na Baía de Todos os Santos têm amplitude moderada, em torno de 2 a 3 metros, mas as correntes geradas pelo movimento da maré nos canais entre as ilhas podem ser intensas e perigosas para embarcações de pequeno porte que navegam sem planejamento adequado.\n\nVoltado para as indústrias petroquímicas e navais, a logística portuária interna na Baía de Todos os Santos exige sincronia com a dinâmica de enchente e vazante. A atracação segura de navios graneleiros ocorre preferencialmente nos períodos de estofo, evitando que correntes intensas afetem os cabos de amarração. Para a comunidade ribeirinha e caiçara do entorno, a extensa área de manguezais só se torna transitável para a catação de mariscos e caranguejos quando a baixamar revela o leito lodoso e os intrincados igarapés da enseada.`,

  'porto-de-salvador': `Salvador é a capital da Bahia e uma das cidades mais ricas culturalmente do Brasil. A cidade está localizada em uma península na entrada da Baía de Todos os Santos, e suas praias — Barra, Ondina, Rio Vermelho e Itapoã — têm condições de banho influenciadas pelas marés do Atlântico Sul. O famoso Farol da Barra, ponto turístico icônico da cidade, está na confluência da Baía de Todos os Santos com o mar aberto, onde as correntes de maré são perceptíveis e devem ser consideradas por nadadores e praticantes de esportes aquáticos.\n\nA maré na baía de Todos os Santos não só define os turnos de atracação comercial, mas pauta a vida turística, náutica e cultural da primeira capital do país. Na maré baixa, as icônicas praias de pedras como a Barra e a Ondina formam poços naturais que encantam banhistas, enquanto a preamar convida aos mergulhos no histórico Porto da Barra. As correntes geradas pela forte troca de água entre o oceano e o estuário tornam o canal de entrada da baía um desafio estimulante para os velejadores baianos.`,

  'porto-de-ilheus': `Ilhéus é uma cidade baiana historicamente ligada à cultura do cacau e cenário do romance "Gabriela, Cravo e Canela" de Jorge Amado. O porto da cidade, localizado na foz do Rio Cachoeira, serve ao escoamento da produção agrícola regional e à pesca artesanal. As praias de Ilhéus — Praia do Sul, Marciano e Cururupe — têm beleza natural preservada e suas condições são influenciadas pelas marés do sul da Bahia. A maré baixa revela piscinas naturais entre as pedras e amplia as faixas de areia das praias, tornando-se o período preferido para caminhadas e mergulho com snorkel.\n\nAs águas que beijam a costa cacaueira baiana movimentam não apenas o escoamento agrícola, mas também o forte turismo local e o surfe. A preamar favorece a atracação de cargueiros e cruzeiros na boca do Rio Cachoeira, atenuando os bancos de areia fluviais. Os surfistas se posicionam de acordo com a variação, buscando o fundo mais propício em praias como Olivença. Na baixamar, a longa extensão de areia plana e escura torna-se a via principal para caminhadas e práticas esportivas à beira-mar de nativos e turistas.`,

  'terminal-de-barra-do-riacho': `O Terminal de Barra do Riacho, em Aracruz (ES), é um importante porto privado do Espírito Santo, especializado na exportação de celulose produzida pelas fábricas da região. Localizado na costa norte capixaba, o terminal opera em águas expostas ao Atlântico Sul, com marés semidiurnas de amplitude moderada. A precisão no monitoramento das marés é importante para as operações de atracação e para a navegação de grandes navios cargueiros que acessam o terminal pela costa aberta.\n\nExposto às intempéries do mar aberto capixaba, o fluxo contínuo de navios que exportam celulose requer janelas climáticas estritas. Embora a variação de maré seja semidiurna e de moderada amplitude, a sua correlação com ressacas sazonais altera severamente a segurança da atracação no píer. As comunidades costeiras ao redor, em Aracruz, se valem das piscinas naturais e recifes que despontam ao longo das praias na maré vazante para alavancar um modesto e belo turismo balnear e também a secular pesca nas pequenas embarcações.`,

  'porto-de-tubarao': `O Porto de Tubarão, em Vitória, é um dos maiores terminais de exportação de minério de ferro do mundo, operado pela Vale. Localizado na Baía de Vitória, o porto opera em ambiente de marés semidiurnas com amplitude entre 1 e 1,5 metros, típica do litoral capixaba. Apesar da amplitude relativamente moderada em comparação ao Norte e Nordeste, o monitoramento das marés é crítico para a operação de navios Capesize e Valemax que carregam centenas de milhares de toneladas de minério por viagem.\n\nO gigante terminal da Vale, debruçado na entrada da Baía de Vitória, opera ininterruptamente o embarque de minério utilizando o ciclo contínuo das águas. A amplitude de maré e as correntes que fluem pelo estuário são fatores cruciais para rebocadores manobrarem embarcações de centenas de metros de comprimento. Para os pescadores do litoral capixaba e os praticantes de esportes à vela ao longo da orla de Camburi, o controle desse pulso aquático orienta desde a navegação costeira segura até a melhor pescaria embarcada no canal.`,

  'porto-de-vitoria': `Vitória é a capital do Espírito Santo e uma das poucas capitais brasileiras localizadas em uma ilha. A Baía de Vitória, que separa a ilha continental do município de Vila Velha, apresenta dinâmica de maré semidiurna com correntes perceptíveis nos canais de navegação durante as trocas. As praias capixabas — Camburi, Curva da Jurema e as praias de Vila Velha — têm condições de banho influenciadas pelas marés do litoral do ES. A maré baixa é o período preferido pelos pescadores de costão que praticam a pesca com vara nas pedras da orla.\n\nA baía estreita que abraça a capital capixaba tem suas correntes fortemente aceleradas pela morfologia afunilada do canal de acesso. Atracar navios no centro urbano exige precisão milimétrica, obrigatoriamente realizada nas calçarias do estofo da maré. Além do tráfego comercial, o ir e vir das marés revitaliza os manguezais da região, sustentando a tradicional panela de barro feita pelas paneleiras que coletam o lodo durante a baixamar. O surfe em picos da vizinha Vila Velha também é diretamente moldado pelo fundo exposto a essas variações.`,

  'ilha-da-trindade': `A Ilha da Trindade é um território brasileiro isolado no Atlântico Sul, localizada a mais de 1.100 km da costa do Espírito Santo. A ilha é administrada pela Marinha do Brasil e abriga uma importante estação científica. Por estar em pleno oceano, suas marés têm características oceânicas puras, com variações menores que as da costa continental. A ilha é um dos sítios de desova de tartarugas marinhas mais importantes do Atlântico Sul, e o monitoramento das marés é parte do trabalho dos pesquisadores que estudam a chegada das tartarugas à praia.\n\nNa isolada base vulcânica oceânica ocupada pela Marinha e por pesquisadores, a ação puramente astronômica dita a lei do mar. A aproximação e o desembarque nas enseadas rochosas íngremes sofrem enormes restrições durante a preamar e em ressacas formadas pelos potentes ventos alísios e swells de sul. Sem a interferência da topografia continental, as medições maregráficas na ilha servem de sentinela avançada para calibrar modelos oceanográficos essenciais no monitoramento global, e a maré vazante é o momento crucial para estudos das tartarugas marinhas e biodiversidade costeira.`,

  'terminal-da-ponta-do-ubu-i': `O Terminal da Ponta do Ubu, em Anchieta (ES), é um porto privado especializado na exportação de ferro-nióbio e outros produtos metalúrgicos. Localizado na costa sul do Espírito Santo, o terminal opera em mar aberto com marés semidiurnas do litoral capixaba. Anchieta é também uma cidade histórica, berço do Padre José de Anchieta, e tem praias preservadas que atraem turistas e pescadores. As marés locais influenciam as condições de pesca na costa rochosa e nas praias de areia da região.\n\nDedicado ao embarque de minérios no litoral sul capixaba, o píer enfrenta o mar aberto, onde a influência conjunta do vento e das ondulações predomina sobre as correntes estuarinas. Apesar do pequeno alcance das marés, a variação batimétrica influencia a estabilidade das atracações pesadas. O turismo de praias charmosas na histórica Anchieta e os pescadores que saem dos ancoradouros rochosos organizam sua rotina pela baixamar, quando o espelho d'água permite a exploração segura dos rochedos e a coleta de mariscos incrustados na costa acidentada.`,

  'terminal-maritimo-de-imbetiba': `Macaé é a "capital do petróleo" brasileiro, sede das principais operações offshore da Petrobras na Bacia de Campos. O Terminal de Imbetiba, em Macaé, é um hub logístico crucial para o abastecimento de plataformas de petróleo. As marés no litoral norte fluminense têm amplitude moderada, mas o monitoramento constante é essencial para as operações de transfer de pessoal e carga entre o porto e as embarcações de apoio offshore. As praias de Macaé — Imbetiba, Cavaleiros e Praia Rasa — têm suas condições influenciadas pelas marés e pela ressurgência de águas frias típica da Bacia de Campos.\n\nA logística intensa de suprimento para as plataformas petrolíferas da Bacia de Campos possui seu ritmo calcado na Baía de Macaé. Os supply boats se beneficiam da preamar para entrar nos atracadouros sem restrição de calado. O fenômeno peculiar da ressurgência, que traz águas frias e riquíssimas em nutrientes para a costa fluminense, interage com as marés locais, criando ciclos curtos de excelente fartura para a pesca comercial, além de definir o banho gelado dos banhistas nas praias da Cavaleiros e Pecado nas vazantes.`,

  'rio-de-janeiro-fiscal': `O Rio de Janeiro é a cidade mais famosa do Brasil e suas praias — Copacabana, Ipanema, Barra da Tijuca e Grumari — são ícones mundiais. As marés na Baía de Guanabara e no litoral oceânico carioca são semidiurnas, com amplitude entre 1 e 1,3 metros. Apesar da variação relativamente pequena, as marés influenciam significativamente as condições das praias: a maré baixa revela bancos de areia, facilita a pesca de costão e é o momento ideal para o surfe em algumas praias. A maré alta traz ondas mais próximas à orla e melhores condições para o bodyboard em Ipanema e Arpoador.\n\nEm meio ao cenário mundialmente famoso da Baía de Guanabara, as correntes geradas pela amplitude térmica e de marés movimentam o denso tráfego de barcas de passageiros, cargueiros e cruzeiros. O estrangulamento geográfico na entrada da baía, próximo ao Pão de Açúcar, cria rebojos notórios nas marés de sizígia que afetam a regata de velejadores profissionais e banhistas na Praia Vermelha. As tábuas da Ilha Fiscal são o farol para surfistas no Arpoador e banhistas em Ipanema e Copacabana que acompanham a subida e recuo do Atlântico.`,

  'porto-de-itaguai': `Itaguaí abriga o Porto de Sepetiba, um dos maiores e mais modernos complexos portuários do Brasil, estrategicamente localizado na Baía de Sepetiba. O porto é especializado em contêineres, automóveis e minérios, e tem crescido rapidamente como alternativa ao congestionado Porto do Rio de Janeiro. A Baía de Sepetiba apresenta condições de maré semidiurna com correntes que devem ser monitoradas pelas embarcações que navegam nos canais de acesso ao porto.\n\nDentro do vasto complexo da Baía de Sepetiba, o terminal lida com águas profundas que abrigam navios cargueiros e grandes rotas de escoamento logístico no eixo Rio-SP. A navegação pesada se beneficia da topografia abrigada, mas requer leitura minuciosa das correntes estuarinas que aceleram durante as marés de sizígia. Na outra ponta, o litoral raso e os extensos manguezais nas franjas da baía garantem a reprodução de dezenas de espécies marinhas e sustentam o intenso turismo náutico que zarpa de Itacuruçá nos finais de semana ensolarados.`,

  'porto-do-forno': `Arraial do Cabo, no Rio de Janeiro, é considerada o "Caribe Brasileiro" por suas águas cristalinas e tonalidades azul-turquesa únicas. O Porto do Forno serve às embarcações de pesca e turismo que operam na região. As correntes de maré em Arraial do Cabo são fortemente influenciadas pela ressurgência de águas frias que caracteriza a região — fenômeno que traz nutrientes da profundeza e é responsável pela extraordinária biodiversidade marinha local. A visibilidade subaquática, que pode chegar a 20 metros, varia conforme as condições de maré e a intensidade da ressurgência.\n\nAs águas cristalinas do Cabo Frio, alimentadas pelo poderoso fenômeno de ressurgência, moldam a vida turística e pesqueira em Arraial do Cabo. As embarcações de pesca costeira e os disputados passeios de barco dependem ativamente das marés para driblar as correntes que esfriam abruptamente o fundo do mar. Na baixamar, os costões rochosos viram um paraíso para mergulhadores em apneia, enquanto a oscilação do nível da preamar ajuda lanchas a se acomodarem confortavelmente na pequena mas essencial infraestrutura do histórico ancoradouro municipal.`,

  'terminal-da-ilha-guaiba': `O Terminal da Ilha Guaíba, em Mangaratiba (RJ), é um porto privado especializado na exportação de minério de ferro. Localizado na Baía de Sepetiba, opera em um ambiente de marés semidiurnas com amplitude moderada. Mangaratiba é também um município turístico, com boa infraestrutura para esportes náuticos e acesso às ilhas da Baía da Ilha Grande — um dos destinos de ecoturismo mais preservados do estado do Rio de Janeiro, onde as condições de navegação e mergulho são fortemente influenciadas pelas marés locais.\n\nLocalizado estrategicamente no interior protegido da Baía de Sepetiba, o porto operado pela Vale exporta milhões de toneladas de minério utilizando o ciclo maregráfico fluminense. As manobras nos canais balizados necessitam da paciência do estofo para garantir o alinhamento das gigantescas proas sem sobrecarga nos equipamentos. Nas redondezas, a variação das águas define a segurança de navegação das famosas escunas de passeio rumo às paradisíacas e recônditas ilhas de Mangaratiba, que frequentemente revelam faixas exclusivas de areia dourada nos momentos de maré morta e vazante.`,

  'porto-do-acu': `O Porto do Açu, em São João da Barra (RJ), é um dos maiores e mais modernos superportos da América Latina, com capacidade para receber navios de grande porte. Localizado no norte fluminense, o porto opera em mar aberto com marés semidiurnas do litoral do Rio de Janeiro. O complexo portuário do Açu é estratégico para o escoamento de petróleo da Bacia de Campos e para a importação de insumos industriais. O monitoramento preciso das marés é crítico para as operações de atracação e para a gestão dos canais de acesso ao porto.\n\nSendo um superporto rasgado através da restinga do norte fluminense, seu canal artificial e profundo impõe uma dinâmica portuária moderna e independente do abrigo natural de baías. A maré regula a logística gigantesca das bases de petróleo e construção naval offshore. Na região circundante de São João da Barra, o avanço constante e severo da maré sobre a costa tem provocado forte erosão nas praias vizinhas. Para os pescadores de Atafona, a maré enchente empurra a cunha salina estuário acima, modificando radicalmente as espécies capturadas.`,

  'porto-de-angra-dos-reis': `Angra dos Reis é um dos destinos turísticos mais sofisticados do Brasil, famosa por suas 365 ilhas, praias paradisíacas e pela proximidade com Ilha Grande — Patrimônio Natural da Humanidade. As marés na Baía da Ilha Grande são semidiurnas, com amplitude entre 1 e 1,2 metros, e influenciam diretamente as condições de navegação entre as ilhas e a qualidade das praias. As melhores condições para ancoragem nos enseadas protegidas, o acesso às praias de difícil chegada e as trilhas de acesso por mar dependem do planejamento dos horários de maré.\n\nO mar cristalino e calmo entre o continente e as mais de trezentas ilhas, destacando-se a monumental Ilha Grande, forma o epicentro do turismo náutico de luxo no Brasil. Os iates e veleiros dependem rigorosamente da preamar para trafegar nos intrincados e rasos canais rochosos, evitando acidentes com pedras submersas e recifes. Para o mergulho nas lajes, o estofo da baixamar oferece as águas mais tranquilas e visibilidade excepcional, fazendo da consulta prévia à tábua de marés um hábito imprescindível para qualquer roteiro turístico neste pedaço protegido da Costa Verde.`,

  'porto-de-sao-sebastiao': `São Sebastião, no litoral norte de São Paulo, é famosa pela travessia de balsa para Ilhabela — a maior ilha costeira do Brasil. O canal de São Sebastião, que separa o continente da ilha, apresenta correntes de maré perceptíveis que afetam a travessia de balsas e embarcações menores. Ilhabela, com suas mais de 80 praias, cachoeiras e trilhas, tem condições de banho e mergulho fortemente influenciadas pelas marés. O arquipélago é um dos melhores destinos de mergulho do Brasil, com naufrágios acessíveis que revelam sua melhor face na maré baixa e com boa visibilidade.\n\nA dinâmica hídrica moldada pelo estreito e profundo Canal de São Sebastião impõe enormes desafios à navegação. Quando as marés enchente ou vazante atingem seu pico, acompanhadas dos frequentes ventos sudoeste, as correntes aceleram velozmente, complicando a vida de navios tanqueiros e gerando atrasos eventuais na travessia de balsa para Ilhabela. As disputadas praias de surf como Maresias e Camburi reagem perfeitamente às oscilações semidiurnas, onde ondas ganham volume ideal nas médias de enchente. A costa recortada e profunda diferencia-se drasticamente do terreno arenoso da vizinha Baixada Santista.`,

  'porto-de-santos': `Santos é a cidade com o maior porto da América Latina e uma das mais importantes cidades portuárias do mundo. O Porto de Santos movimenta cerca de 30% de toda a balança comercial brasileira. As marés em Santos são semidiurnas, com amplitude entre 1 e 1,5 metros, e influenciam diretamente as operações de atracação e a navegação no Canal de Santos. As praias da cidade — a mais longa orla urbana do mundo com 7 km — têm suas condições de banho afetadas pelas marés, com a maré baixa revelando maior extensão de areia e a maré cheia trazendo o mar mais próximo da orla histórica.\n\nO Porto de Santos não é apenas o mais importante do Brasil, mas também o maior da América Latina, e sua operação depende intrinsicamente da dinâmica das águas. A variação das marés influencia de forma decisiva as complexas operações de atracação e desatracação dos navios cargueiros gigantes que cruzam o Canal de Santos diariamente. Além de pautar o ritmo comercial e logístico, as marés de Santos atuam como a referência oficial de medição para toda a Baixada Santista e litoral adjacente. Com uma orla urbana contínua de 7 quilômetros de extensão, as famosas praias santistas mudam de cenário constantemente: durante as sizígias, a maré cheia aproxima o oceano dos famosos jardins da orla, enquanto a baixamar revela uma longa e plana faixa de areia perfeita para a prática de esportes e caminhadas.`,

  // Litoral SP
  'guaruja': `O Guarujá é o destino de praia mais procurado pelos paulistanos, distante apenas 90 km da capital por rodovia. Com praias como Pitangueiras, Enseada, Perequê e Tombo, o município recebe milhões de turistas por ano, especialmente nos finais de semana e feriados. As marés do Guarujá são referenciadas pela estação de Santos e têm amplitude semidiurna de cerca de 1 a 1,5 metros. A maré baixa na Praia do Tombo cria condições ideais para o surfe, enquanto na Enseada e Pitangueiras a maré cheia é preferida pelos banhistas pela maior profundidade e menor exposição ao fundo rochoso.\n\nA influência da maré nas diferentes praias do Guarujá é um fator determinante para aproveitar o dia. Na Praia do Tombo, a maré baixa é a mais cobiçada pelos surfistas, pois ajuda a formar os famosos tubos e ondas consistentes. Já nas badaladas praias da Enseada e Pitangueiras, o período de preamar é perfeito para o banho, garantindo uma profundidade agradável sem tanta exposição aos bancos de areia e buracos. Para os pescadores do entorno, o canal do Perequê torna-se mais produtivo na virada da maré, atraindo cardumes próximos da orla. O porto de referência oficial para a região é Santos, localizado a aproximadamente 5 km de distância. Além do lazer, a maré afeta diretamente a logística local: em dias de marés vivas intensas, o embarque e desembarque na travessia de balsa Guarujá–Santos pode sofrer atrasos devido à forte correnteza e variações severas na rampa de acesso.`,

  'sao-vicente': `São Vicente é considerada a cidade mais antiga do Brasil, fundada em 1532, e faz parte da Baixada Santista junto com Santos e Guarujá. Suas praias — Itararé, Milionários e Gonzaguinha — são opções populares e mais tranquilas que as de Santos. As marés em São Vicente são praticamente idênticas às de Santos, com amplitude semidiurna entre 1 e 1,5 metros. A orla de São Vicente tem características diferentes de Santos — com pedras e costões rochosos que ficam expostos na maré baixa, criando piscinas naturais e condições propícias para a pesca de costão.\n\nA baía protegida de São Vicente faz da cidade um dos berços da navegação de lazer e pesca amadora no litoral sul de São Paulo. A maré baixa expõe amplos bancos de areia e os famosos costões rochosos no Itararé e Porchat, locais cobiçados por praticantes de pesca de arremesso que acompanham ansiosamente a tabela da preamar. O estreito Canal dos Barreiros se comporta de maneira peculiar e veloz durante a mudança de sentido, exigindo cautela de pequenas embarcações. Os dados oficiais acompanham inteiramente a régua portuária de sua vizinha direta, Santos.`,

  'praia-grande': `Praia Grande é o município paulista com a maior concentração de apartamentos por metro quadrado do Brasil, um destino massivo de verão para famílias do interior de São Paulo. Com uma orla de 22 km dividida em praias como Ocian, Caiçara, Aviação e Boqueirão, a cidade recebe milhões de turistas na alta temporada. As marés em Praia Grande têm uma pequena defasagem de cerca de 5 minutos em relação a Santos, com amplitude semidiurna similar. A maré baixa revela bancos de areia rasos ideais para crianças e facilita os passeios de pedalinho nas praias centrais.\n\nCom seus longos vinte e dois quilômetros contínuos de areia batida, a cidade recebe milhões de banhistas que encontram uma relação íntima com a variação das águas. Na preamar, ondas curtas chegam próximas ao calçadão nas marés de sizígia, ao passo que a baixamar entrega o famoso cenário de planície sem fim, perfeito para as incontáveis peladas de futebol e ciclistas na areia rígida. A geografia desprovida de ilhas deixa a costa exposta às ondulações frontais. A tábua possui um leve atraso na previsão comparado a Santos.`,

  'bertioga': `Bertioga é um município do litoral norte de São Paulo, separado do Guarujá pelo Canal de Bertioga — um dos canais históricos mais importantes da colonização brasileira. As praias de Bertioga — como Riviera, Vista Linda e São Lourenço do Sul — são mais preservadas e menos movimentadas que as da Baixada Santista. As marés em Bertioga têm uma defasagem de cerca de 15 minutos em relação a Santos e influenciam diretamente as condições de navegação no canal histórico, frequentado por embarcações de pesca e lazer.\n\nO extenso e histórico Canal de Bertioga é um ecossistema à parte que fervilha com os amantes da pesca esportiva e das frotas de escunas turísticas. A vazante afasta a água salgada, impulsionando a descida do fluxo da Serra do Mar e criando bolsões ideais de alimentação para peixes nas galhadas, sendo o momento mágico aguardado por piloteiros. Geograficamente localizado no fim da restinga santista e início do acidentado litoral norte, apresenta uma defasagem e comportamento batimétrico próprio, embora as previsões oficiais usem Santos como referência mãe para cálculos operacionais.`,

  'riviera-de-sao-lourenco': `A Riviera de São Lourenço é um dos condomínios residenciais de praia mais sofisticados do Brasil, com infraestrutura completa e praias organizadas. Localizada em Bertioga, no litoral norte paulista, a Riviera tem uma orla bem cuidada com estrutura de apoio para esportes aquáticos. As marés nessa região têm as mesmas características de Bertioga, com defasagem de 15 minutos em relação a Santos. A maré baixa na Riviera revela uma extensa faixa de areia que se estende até a foz do Rio São Lourenço, criando condições ideais para caminhadas e esportes de praia.\n\nO famoso condomínio planejado de alto padrão lida com a dinâmica de enchente e vazante moldando tanto a badalada praia quanto o encontro do pacato rio São Lourenço com o mar. A maré enchente proporciona banhos de alta qualidade em águas geralmente mais claras trazidas pelo fluxo oceânico. Na baixamar, os surfistas frequentam o píer à direita onde os bancos de areia ajudam a moldar ondas de formato clássico. A defasagem em relação ao referencial de Santos exige atenção para a prática de esportes à vela no rio.`,

  'mongagua': `Mongaguá é um município da Baixada Santista conhecido como destino familiar e alternativa mais tranquila às praias de Santos e Praia Grande. Com praias como Agenor de Campos e Flórida, a cidade tem uma orla preservada com menos estrutura urbana e mais contato com a natureza. As marés em Mongaguá têm uma defasagem de cerca de 10 minutos em relação a Santos. A maré baixa em Mongaguá revela bancos de areia e permite longas caminhadas pela orla, enquanto a maré alta traz o mar mais próximo da vegetação costeira remanescente.\n\nFamosa por sua tradicional Plataforma de Pesca, a maior de concreto armado avançando sobre o mar na América Latina, a cidade tem seu principal atrativo completamente dominado pelas oscilações das ondas e da maré oceânica. A enchente arrasta nutrientes para próximo dos pilares, transformando o local num ponto excepcional para a captura com iscas naturais. A orla reta e desprovida de enseadas protetoras faz com que a preamar avance furiosamente na praia plana durante os dias de ressaca. O pequeno atraso em relação à baía santista afeta levemente os horários da região.`,

  'itanhaem': `Itanhaém é uma das cidades mais antigas de São Paulo e tem a maior extensão de praia do litoral sul paulista, com mais de 40 km de costa praticamente ininterrupta. A cidade é um destino de praia popular entre famílias que buscam mais tranquilidade e natureza preservada. As marés em Itanhaém têm uma defasagem de 15 minutos em relação a Santos, com amplitude semidiurna similar. A maré baixa em Itanhaém revela extensos bancos de areia e a foz dos rios que deságuam na praia, criando condições únicas para pesca de arremesso e passeios a pé.\n\nBerço da colonização, o complexo estuarino raso formado pelos formidáveis rios Itanhaém, Preto e Branco sofre pesada interferência diária do mar. A subida da maré força o avanço da cunha salina por vários quilômetros continente adentro, fenômeno imprescindível para o turismo de pequenos barcos que navegam rumo às regiões de manguezal e mata atlântica nativa. Nas praias do Camaço e Sonho, a variação da profundidade define desde os dias seguros para banhistas até a qualidade da famosa pesca do robalo na boca da barra do rio, referenciada pelas previsões oficiais de Santos.`,

  'peruibe': `Peruíbe é o município mais ao sul da Baixada Santista e um dos destinos de natureza mais preservados do litoral paulista, próximo à APA da Serra do Mar e ao Parque Estadual do Prelado. As praias de Peruíbe — como Praia do Centro, Barra do Una e Guarauzinho — têm características mais selvagens e são frequentadas por quem busca sossego e contato com a natureza. As marés em Peruíbe têm defasagem de 20 minutos em relação a Santos e amplitude semidiurna de cerca de 1 a 1,3 metros, influenciando o acesso às praias mais isoladas da região.\n\nO limite final das planícies do litoral sul desfruta do encontro espetacular entre a praia e as altas encostas verdes da Estação Ecológica Juréia-Itatins. Nas praias urbanas, a baixamar convida moradores para caminhadas na firme faixa úmida e a pesca de beira. Nas rústicas praias da reserva como Guaraú e Caramborê, a dinâmica dos pequenos estuários isolados que rompem a barra na vazante orienta a vida selvagem, a reprodução de aves e as travessias turísticas guiadas em caiaque e pequenas pranchas de stand-up. Utiliza-se Santos com uma defasagem mais pronunciada.`,

  // ── Região Sul ────────────────────────────────────────────────────────────

  'barra-de-paranagua-sueste': `A Barra de Paranaguá pelo Canal Sueste é uma das entradas marítimas mais movimentadas do sul do Brasil, utilizada por navios que acessam o Porto de Paranaguá pelo canal mais curto. A região da Barra é conhecida por suas correntes intensas durante as trocas de maré, especialmente nos períodos de sizígia, quando a diferença entre preamar e baixamar é máxima. Pilotos de barra e práticos que operam nessa região acumulam décadas de conhecimento sobre o comportamento das marés e correntes nos canais estuarinos da Baía de Paranaguá.\n\nA complexa aproximação marítima para a segunda maior baía do Brasil exige respeito aos temidos baixios do litoral paranaense. A navegação pesada na boca da barra e no canal sueste depende visceralmente das enchentes para não arriscar os cascos dos graneleiros em fundos de areia rasos. As correntes geradas pela forte saída da imensa quantidade de água estuarina formam zonas de turbulência intensas que pescadores oceânicos aproveitam para farta pesca de arrasto e corrico, desde que respeitados os severos horários do ciclo da tábua semidiurna.`,

  'porto-de-paranagua': `Paranaguá abriga o maior porto exportador de grãos da América Latina e um dos maiores do mundo. O Porto de Paranaguá, localizado no estuário da Baía de Paranaguá, opera em condições de maré semidiurna com amplitude entre 1,5 e 2 metros. A variação de maré é fundamental para o gerenciamento do calado dos navios graneleiros que carregam soja, milho e outros grãos com margens de segurança mínimas. A baía também é um dos maiores estuários do sul do Brasil, com ecossistemas de manguezal preservados que dependem do ciclo das marés para sua saúde ecológica.\n\nAs operações multimodais do megaporto graneleiro do Paraná estão intrinsecamente amarradas ao relógio da variação das águas da grande e protegida baía. Navios de longo curso desfrutam da calmaria estuarina, mas sua atracação só é autorizada nos estofos que atenuam a pressão mecânica contra os defensas dos píeres. O vasto sistema de estuários adjacentes ao porto garante o abrigo da frota pesqueira regional que lança suas redes ao sabor das marés enchentes e é a fonte fundamental da extração do famoso caranguejo uçá comercializado no litoral.`,

  'barra-de-paranagua-galheta': `O Canal da Galheta é o principal acesso marítimo ao Porto de Paranaguá, utilizado por navios de maior calado. Com profundidade maior que o Canal Sueste, a Galheta é preferida pelos navios graneleiros e tanqueiros que acessam os terminais do complexo portuário de Paranaguá. As correntes no canal são geradas principalmente pelo fluxo de maré e pela descarga dos rios que alimentam a Baía de Paranaguá, tornando o monitoramento preciso das marés indispensável para a navegação segura nesse trecho.\n\nDestinado aos navios de grandíssimo calado, o sinuoso canal e sua morfologia escavada exigem sincronismo total da praticagem. A topografia submarina restrita causa um efeito de funil, elevando drasticamente a força das correntes de maré que empurram os paredões rochosos próximos da Ilha do Mel. Surfistas acompanham avidamente as ondulações nas praias do istmo e de Fora na ilha, que quebram de maneira singular devido às correntes da foz estuarina interagindo com os fortes swells de leste na baixa das tábuas semidiurnas paranaenses.`,

  'terminal-portuario-da-ponta-do-felix': `O Terminal Portuário da Ponta do Félix, em Antonina (PR), é um porto privado localizado no fundo da Baía de Paranaguá, especializado em granéis sólidos e líquidos. Por estar no extremo interior da baía, as marés em Antonina chegam com uma defasagem de aproximadamente 1 hora em relação à barra, e a amplitude é ligeiramente reduzida pelo efeito do percurso estuarino. A cidade de Antonina é uma das mais antigas do Paraná e tem um cais histórico que complementa a atividade portuária moderna do terminal privado.\n\nNo fundo extremo da Baía de Antonina, a calmaria aparente esconde uma navegação meticulosa feita através dos sinuosos canais de calado restrito cercados por mata atlântica. A cidade histórica e seu atracadouro lidam com enchentes que demoram até uma hora a mais para alcançarem seus níveis máximos em relação à barra marítima. A pesca estuarina e o passeio de barco tradicional com barreado no porto de Antonina dependem das preamares, sem as quais os saveiros rasgariam os fundos nas intermináveis coroas de lama que surgem com a baixamar.`,

  'porto-de-sao-francisco-do-sul': `São Francisco do Sul, em Santa Catarina, é o terceiro porto mais antigo do Brasil e o principal terminal graneleiro do estado. Localizado em uma ilha, o município tem um centro histórico bem preservado e um porto que movimenta grandes volumes de grãos, fertilizantes e automóveis. As marés no Canal do Linguado, que separa a ilha do continente, são semidiurnas com amplitude entre 0,8 e 1,2 metros. As praias da ilha — Ubatuba, Prainha e Paulas — têm suas condições de banho e pesca influenciadas pelas marés do litoral norte catarinense.\n\nO terceiro município mais antigo do país abraça um modelo de porto-ilha onde o braço de mar denominado Canal do Linguado impõe sua vontade a marinheiros e operadores. O escoamento formidável das safras e laminados é favorecido pelo estuário seguro, desde que amparado pelas janelas curtas de estofo para manobras entre as ilhas oceânicas da baía da Babitonga. Praias vibrantes como a da Enseada se transformam: a vazante alarga a areia e revela a restinga nativa preservada, fomentando turismo contínuo nas quatro estações.`,

  'porto-de-itajai': `Itajaí é um dos maiores portos de contêineres da América do Sul e o principal porto de Santa Catarina. Localizado na foz do Rio Itajaí-Açu, o porto opera em ambiente de marés semidiurnas com amplitude entre 0,8 e 1,2 metros, mas com correntes significativas geradas pelo fluxo do rio — especialmente em períodos de chuva intensa no Vale do Itajaí. A cidade de Itajaí e as vizinhas Balneário Camboriú e Navegantes têm suas praias influenciadas pelas marés do litoral central catarinense, com a maré baixa revelando extensas faixas de areia.\n\nO vigoroso caudal do Rio Itajaí-Açu mistura-se com as águas oceânicas formando correntes implacáveis no centro da logística naval catarinense. Durante as chuvas da bacia, aliadas à maré vazante, o fluxo empurra embarcações na barra, obrigando a paralisação por questões de segurança na estiva de contêineres e na saída das badaladas frotas de cruzeiros de passageiros. Pescadores e praticantes de surf da vizinha Praia Brava sabem que, na maré baixa, os bancos de areia estabilizam, gerando excelentes picos tubulares bem próximos do balneário vizinho, Balneário Camboriú.`,

  'porto-de-florianopolis': `Florianópolis é a capital de Santa Catarina e um dos destinos de praia mais procurados do Brasil, famosa por suas mais de 100 praias distribuídas em uma ilha e numa pequena porção continental. As marés em Florianópolis são semidiurnas, com amplitude entre 0,5 e 1 metro — menor que no norte e nordeste, mas com impacto significativo nas condições de praias como Joaquina, Mole, Barra da Lagoa e Campeche. A Lagoa da Conceição, conectada ao mar, tem seu nível influenciado pelas marés através do canal da Barra da Lagoa, criando correntes que são aproveitadas pelos praticantes de windsurf e kitesurf.\n\nEmbora abrigue menos calado comercial na baía norte e sul, o pulsar marinho é quem coordena a mágica da famosa e cobiçada Ilha da Magia. O fenômeno peculiar das pontes que interligam os dois lados sofre correntes marcantes na estreita faixa do continente. O surfe mundial em locais clássicos como Joaquina e a preservada Campeche exige alinhamento entre vento sul e as marés médias de enchente para quebrar perfeito nos bancos de areia. A célebre Lagoa da Conceição drena ou preenche volumes colossais pelo Canal da Barra em harmonia total com as marés.`,

  'porto-de-imbituba': `Imbituba é um município catarinense que combina atividade portuária com turismo de natureza. A cidade é um dos principais pontos de observação de baleias-francas do Brasil — os cetáceos chegam à costa entre junho e novembro para se reproduzir nas águas mais quentes do litoral sul. As marés em Imbituba são semidiurnas com amplitude moderada, e as baleias utilizam as enseadas protegidas durante os períodos de maré mais calma para amamentação dos filhotes. O porto de Imbituba movimenta principalmente cerâmica e produtos regionais.\n\nAncorado em uma enseada naturalmente desenhada em formato de ferradura e com águas profundas de mar aberto, opera distante das incertezas geográficas estuarinas. Apesar da atracação facilitada e de menor oscilação da preamar local, os navios enfrentam as intensas ressacas invernais do Atlântico sul. O município se orgulha de ser o berçário da formidável Baleia Franca, cuja presença atrai fortíssimo turismo sustentável; passeios embarcados e o surf nos picos de Ibiraquera e Rosa reagem prontamente à virada das tábuas marítimas catarinenses.`,

  'porto-do-rio-grande': `Rio Grande, no extremo sul do Brasil, abriga o único porto marítimo do Rio Grande do Sul e uma das cidades mais frias do litoral brasileiro. Localizado na entrada da Lagoa dos Patos — a maior laguna da América do Sul —, o porto opera em condições únicas de maré influenciadas tanto pelo Atlântico Sul quanto pela dinâmica da laguna. As correntes na barra de Rio Grande podem ser intensas e imprevisíveis, combinando o efeito das marés com os ventos predominantes do sul e o volume d'água da Lagoa dos Patos.\n\nNa barra mais temida e instável do Brasil extremo, os encontros colossais das águas da vasta Lagoa dos Patos com os furiosos swells oceânicos e fortes ventos do quadrante sul anulam e potencializam os efeitos das marés astronômicas, gerando marés meteorológicas brutais. Os monumentais molhes da barra abrigam não apenas navios aguardando janela na preamar, mas legiões de turistas e pescadores de final de semana em vagonetas exóticas. A variação das águas define a prosperidade de centenas de famílias extratoras de mariscos incrustados nos estuários adjacentes.`,

  'base-comandante-ferraz': `A Base Antártica Comandante Ferraz, localizada na Baía do Almirantado na Ilha Rei George, é a estação científica brasileira na Antártida. As marés na Antártida têm características únicas, com componentes complexas resultantes da geometria do oceano Austral. A amplitude varia conforme a localização, mas o monitoramento preciso é fundamental para as operações logísticas da base — especialmente o desembarque de materiais e combustível por barcaças, que dependem de condições específicas de maré e de mar para segurança da operação.\n\nNa Baía do Almirantado, enxames de gelo fragmentado, pinguins e icebergs convivem no ambiente extremo operado pela briosa estação antártica brasileira. A peculiaridade batimétrica antártica traz ciclos diários irregulares combinados com ondas intensificadas pela ausência prolongada de luz e bloqueios terrestres. As marés altas são cruciais no breve verão para que pequenas barcaças encostem e superem as faixas cascalhadas geladas, garantindo os preciosos suprimentos de diesel, água fresca e instrumentos cruciais que mantêm vivas as heroicas pesquisas climáticas no continente mais hostil do planeta.`,

};

/**
 * Retorna a descrição única do porto pelo slug.
 * Se não encontrar, retorna string vazia para manter compatibilidade.
 */
export function getPortoDescription(slug: string): string {
  return portoDescriptions[slug] ?? '';
}

export default portoDescriptions;
