name: Cherry-pick JSON data

on:
  workflow_dispatch:

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch and apply orphan commit
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git fetch origin refs/heads/main:refs/remotes/origin/main
          git fetch --all
          git fetch origin +e43075c:refs/remotes/origin/orphan
          git cherry-pick refs/remotes/origin/orphan

      - name: Push to main
        run: git push origin main
